import type { SignalEvent, WatchlistAccount, ICPAccount, PlaybookData, PlaybookListItem, AccountDetails } from "./types";

// Helper: ISO date N days ago
function daysAgo(n: number): string {
  const d = new Date("2026-05-17T00:00:00.000Z");
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

// ---------------------------------------------------------------------------
// MOCK_SIGNALS
// ---------------------------------------------------------------------------

export const MOCK_SIGNALS: SignalEvent[] = [
  {
    id: "sig-001",
    type: "new_funding",
    headline: "$50M Series D led by a16z",
    summary: "Round signals aggressive product expansion and a larger 2026 tooling budget. Net-new tier likely.",
    detectedAt: daysAgo(1),
    source: "Crunchbase",
    seenAt: null,
    accountId: "acc-lattice",
  },
  {
    id: "sig-002",
    type: "hiring_surge",
    headline: "34 new GTM & engineering roles",
    summary: "Sales and engineering reqs opened this week — a significant GTM ramp ahead of their annual Celebrate conference.",
    detectedAt: daysAgo(2),
    source: "LinkedIn Jobs",
    seenAt: daysAgo(1),
    accountId: "acc-gong",
  },
  {
    id: "sig-003",
    type: "intent_surge",
    headline: "Heavy research on \"revenue intelligence\"",
    summary: "Outreach team has been researching revenue intelligence and conversation analytics across 14 properties.",
    detectedAt: daysAgo(3),
    source: "Bombora",
    seenAt: null,
    accountId: "acc-outreach",
  },
  {
    id: "sig-004",
    type: "tech_change",
    headline: "Migrated from Marketo to HubSpot",
    summary: "Switch creates a window for complementary tooling that integrates with HubSpot natively.",
    detectedAt: daysAgo(2),
    source: "BuiltWith",
    seenAt: null,
    accountId: "acc-salesloft",
  },
  {
    id: "sig-005",
    type: "leadership_change",
    headline: "New CRO hired from Salesforce",
    summary: "New revenue leaders typically audit the full sales stack within 90 days of joining.",
    detectedAt: daysAgo(4),
    source: "LinkedIn",
    seenAt: daysAgo(3),
    accountId: "acc-qualified",
  },
  {
    id: "sig-006",
    type: "expansion",
    headline: "Opened a new EMEA office in London",
    summary: "APAC and EMEA headcount targets doubled for the year; localization and enterprise hiring follow this pattern.",
    detectedAt: daysAgo(5),
    source: "6sense Newsroom",
    seenAt: null,
    accountId: "acc-6sense",
  },
  {
    id: "sig-007",
    type: "new_funding",
    headline: "Raised $225M Series F at $1.6B valuation",
    summary: "They will likely expand their platform and partner ecosystem aggressively over the next 18 months.",
    detectedAt: daysAgo(0),
    source: "TechCrunch",
    seenAt: null,
    accountId: "acc-clari",
  },
  {
    id: "sig-008",
    type: "hiring_surge",
    headline: "18 SDRs + 4 Sales Engineers roles open",
    summary: "Strong signal they are entering a new market segment — decision velocity is high right now.",
    detectedAt: daysAgo(6),
    source: "LinkedIn Jobs",
    seenAt: daysAgo(5),
    accountId: "acc-bombora",
  },
  {
    id: "sig-009",
    type: "intent_surge",
    headline: "Active research on data enrichment alternatives",
    summary: "Buying committee has been researching real-time visitor identification — suggesting active vendor evaluation.",
    detectedAt: daysAgo(1),
    source: "Bombora",
    seenAt: null,
    accountId: "acc-clearbit",
  },
  {
    id: "sig-010",
    type: "tech_change",
    headline: "Switched from Salesforce to HubSpot CRM",
    summary: "Ideal moment to introduce complementary ABM tooling that integrates natively with HubSpot.",
    detectedAt: daysAgo(7),
    source: "BuiltWith",
    seenAt: daysAgo(6),
    accountId: "acc-demandbase",
  },
  {
    id: "sig-011",
    type: "leadership_change",
    headline: "New VP Sales Engineering, ex-Snowflake",
    summary: "Track record of modernizing the pre-sales tech stack at Snowflake — a tailwind for our category.",
    detectedAt: daysAgo(3),
    source: "LinkedIn",
    seenAt: null,
    accountId: "acc-lattice",
  },
  {
    id: "sig-012",
    type: "expansion",
    headline: "Launched a mid-market product tier",
    summary: "New SKU opens a segment they previously left to competitors. Worth re-pricing the open opp.",
    detectedAt: daysAgo(8),
    source: "Gong Blog",
    seenAt: daysAgo(7),
    accountId: "acc-gong",
  },
  {
    id: "sig-013",
    type: "new_funding",
    headline: "Closed a $95M growth round",
    summary: "Confirms a multi-year investment horizon for their Pipeline Cloud platform expansion.",
    detectedAt: daysAgo(9),
    source: "Crunchbase",
    seenAt: daysAgo(8),
    accountId: "acc-qualified",
  },
  {
    id: "sig-014",
    type: "hiring_surge",
    headline: "22 RevOps & data roles posted this week",
    summary: "Strong indicator they are investing in their analytics infrastructure — opens tooling conversations.",
    detectedAt: daysAgo(2),
    source: "LinkedIn Jobs",
    seenAt: null,
    accountId: "acc-clari",
  },
  {
    id: "sig-015",
    type: "intent_surge",
    headline: "Spiked on pipeline generation research",
    summary: "Team researching outbound automation topics — may be evaluating tooling to supplement native ABM.",
    detectedAt: daysAgo(4),
    source: "Bombora",
    seenAt: null,
    accountId: "acc-6sense",
  },
  {
    id: "sig-016",
    type: "tech_change",
    headline: "Replaced Drift with Qualified for pipeline",
    summary: "Active vendor consolidation cycle — indicating openness to new conversational sales tooling.",
    detectedAt: daysAgo(10),
    source: "BuiltWith",
    seenAt: daysAgo(9),
    accountId: "acc-outreach",
  },
  {
    id: "sig-017",
    type: "leadership_change",
    headline: "VP of Product promoted to Chief Product Officer",
    summary: "Internal leadership transitions often spark a reassessment of vendor relationships.",
    detectedAt: daysAgo(11),
    source: "LinkedIn",
    seenAt: daysAgo(10),
    accountId: "acc-bombora",
  },
];

// ---------------------------------------------------------------------------
// MOCK_WATCHLIST_ACCOUNTS
// ---------------------------------------------------------------------------

export const MOCK_WATCHLIST_ACCOUNTS: WatchlistAccount[] = [
  {
    id: "acc-lattice",
    accountName: "Lattice",
    domain: "lattice.com",
    description: "People management platform helping HR and people teams run performance reviews, set goals, and develop employees. Primarily serves mid-market and enterprise companies scaling their people operations.",
    industry: "SaaS",
    revenue: "$50M–$100M ARR",
    employees: "501–1,000",
    location: "San Francisco, CA",
    addedAt: daysAgo(14),
    monitoredSignals: ["new_funding", "leadership_change", "hiring_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-lattice"),
    intentScore: 87,
    intentDelta: 11,
    intentLabel: "Hot",
  },
  {
    id: "acc-gong",
    accountName: "Gong",
    domain: "gong.io",
    description: "Revenue intelligence platform that captures and analyzes customer interactions across calls, emails, and meetings. Helps sales teams understand what's working and coach reps at scale.",
    industry: "SaaS",
    revenue: "$100M+ ARR",
    employees: "1,001–5,000",
    location: "San Francisco, CA",
    addedAt: daysAgo(20),
    monitoredSignals: ["hiring_surge", "expansion", "intent_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-gong"),
    intentScore: 92,
    intentDelta: 6,
    intentLabel: "Hot",
  },
  {
    id: "acc-outreach",
    accountName: "Outreach",
    domain: "outreach.io",
    description: "Sales execution platform for sequencing, prospecting, and pipeline management. Used by outbound sales teams to automate multi-channel outreach and surface deal risk early.",
    industry: "SaaS",
    revenue: "$100M+ ARR",
    employees: "1,001–5,000",
    location: "Seattle, WA",
    addedAt: daysAgo(5),
    monitoredSignals: ["intent_surge", "tech_change"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-outreach"),
    intentScore: 81,
    intentDelta: 4,
    intentLabel: "Hot",
  },
  {
    id: "acc-salesloft",
    accountName: "Salesloft",
    domain: "salesloft.com",
    description: "Sales engagement and revenue workflow platform. Helps revenue teams manage cadences, forecast deals, and coach sellers through the full sales cycle from prospecting to close.",
    industry: "SaaS",
    revenue: "$50M–$100M ARR",
    employees: "501–1,000",
    location: "Atlanta, GA",
    addedAt: daysAgo(10),
    monitoredSignals: ["tech_change", "hiring_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-salesloft"),
    intentScore: 55,
    intentDelta: -3,
    intentLabel: "Warm",
  },
  {
    id: "acc-qualified",
    accountName: "Qualified",
    domain: "qualified.com",
    description: "Pipeline generation platform for B2B companies using Salesforce. Identifies high-intent website visitors in real time and enables sales reps to engage them instantly via chat and AI agents.",
    industry: "SaaS",
    revenue: "$10M–$50M ARR",
    employees: "101–500",
    location: "San Francisco, CA",
    addedAt: daysAgo(7),
    monitoredSignals: ["leadership_change", "new_funding"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-qualified"),
    intentScore: 91,
    intentDelta: 8,
    intentLabel: "Hot",
  },
  {
    id: "acc-6sense",
    accountName: "6sense",
    domain: "6sense.com",
    description: "Account engagement platform using AI and intent data to surface in-market buyers. Helps B2B revenue teams prioritize accounts, personalize outreach, and forecast pipeline with predictive insights.",
    industry: "SaaS",
    revenue: "$100M+ ARR",
    employees: "1,001–5,000",
    location: "San Francisco, CA",
    addedAt: daysAgo(3),
    monitoredSignals: ["expansion", "intent_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-6sense"),
    intentScore: 78,
    intentDelta: -2,
    intentLabel: "Hot",
  },
  {
    id: "acc-clari",
    accountName: "Clari",
    domain: "clari.com",
    description: "Revenue operations platform that consolidates CRM data, call intelligence, and activity signals into a single forecast. Used by CROs and RevOps teams to eliminate revenue leak and improve win rates.",
    industry: "SaaS",
    revenue: "$100M+ ARR",
    employees: "501–1,000",
    location: "Sunnyvale, CA",
    addedAt: daysAgo(25),
    monitoredSignals: ["new_funding", "hiring_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-clari"),
    intentScore: 83,
    intentDelta: 9,
    intentLabel: "Hot",
  },
  {
    id: "acc-bombora",
    accountName: "Bombora",
    domain: "bombora.com",
    description: "B2B intent data provider aggregating content consumption signals from a cooperative of publisher websites. Helps marketing and sales teams identify accounts actively researching solutions in their category.",
    industry: "SaaS",
    revenue: "$10M–$50M ARR",
    employees: "101–500",
    location: "New York, NY",
    addedAt: daysAgo(18),
    monitoredSignals: ["hiring_surge", "leadership_change"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-bombora"),
    intentScore: 44,
    intentDelta: -14,
    intentLabel: "Warm",
  },
  {
    id: "acc-clearbit",
    accountName: "Clearbit",
    domain: "clearbit.com",
    description: "B2B data enrichment platform providing real-time firmographic, technographic, and contact data. Widely used to enrich CRM records, power lead scoring, and personalise marketing and sales workflows.",
    industry: "SaaS",
    revenue: "$10M–$50M ARR",
    employees: "101–500",
    location: "San Francisco, CA",
    addedAt: daysAgo(30),
    monitoredSignals: ["intent_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-clearbit"),
    intentScore: 31,
    intentDelta: -5,
    intentLabel: "Cold",
  },
  {
    id: "acc-demandbase",
    accountName: "Demandbase",
    domain: "demandbase.com",
    description: "Account-based marketing and sales intelligence platform. Combines first-party intent, advertising, and CRM data to help B2B teams identify, engage, and convert their highest-value target accounts.",
    industry: "SaaS",
    revenue: "$50M–$100M ARR",
    employees: "501–1,000",
    location: "San Francisco, CA",
    addedAt: daysAgo(12),
    monitoredSignals: ["tech_change", "intent_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-demandbase"),
    intentScore: 58,
    intentDelta: 3,
    intentLabel: "Warm",
  },
];

// ---------------------------------------------------------------------------
// MOCK_ICP_RESULTS
// ---------------------------------------------------------------------------

export const MOCK_ICP_RESULTS: ICPAccount[] = [
  { id: "icp-001", companyName: "Lattice", domain: "lattice.com", industry: "SaaS", revenue: "$50M–$100M", employees: 750, location: "San Francisco, CA", icpScore: 96, isWatched: true },
  { id: "icp-002", companyName: "Gong", domain: "gong.io", industry: "SaaS", revenue: "$100M+", employees: 2400, location: "San Francisco, CA", icpScore: 94, isWatched: true },
  { id: "icp-003", companyName: "Clari", domain: "clari.com", industry: "SaaS", revenue: "$100M+", employees: 800, location: "Sunnyvale, CA", icpScore: 92, isWatched: true },
  { id: "icp-004", companyName: "Qualified", domain: "qualified.com", industry: "SaaS", revenue: "$10M–$50M", employees: 250, location: "San Francisco, CA", icpScore: 91, isWatched: true },
  { id: "icp-005", companyName: "6sense", domain: "6sense.com", industry: "SaaS", revenue: "$100M+", employees: 1800, location: "San Francisco, CA", icpScore: 89, isWatched: true },
  { id: "icp-006", companyName: "Outreach", domain: "outreach.io", industry: "SaaS", revenue: "$100M+", employees: 1200, location: "Seattle, WA", icpScore: 88, isWatched: true },
  { id: "icp-007", companyName: "Salesloft", domain: "salesloft.com", industry: "SaaS", revenue: "$50M–$100M", employees: 600, location: "Atlanta, GA", icpScore: 86, isWatched: true },
  { id: "icp-008", companyName: "Chorus.ai", domain: "chorus.ai", industry: "SaaS", revenue: "$10M–$50M", employees: 320, location: "San Francisco, CA", icpScore: 84, isWatched: false },
  { id: "icp-009", companyName: "Highspot", domain: "highspot.com", industry: "SaaS", revenue: "$50M–$100M", employees: 550, location: "Seattle, WA", icpScore: 83, isWatched: false },
  { id: "icp-010", companyName: "Seismic", domain: "seismic.com", industry: "SaaS", revenue: "$50M–$100M", employees: 700, location: "San Diego, CA", icpScore: 81, isWatched: false },
  { id: "icp-011", companyName: "Bombora", domain: "bombora.com", industry: "SaaS", revenue: "$10M–$50M", employees: 280, location: "New York, NY", icpScore: 79, isWatched: true },
  { id: "icp-012", companyName: "Clearbit", domain: "clearbit.com", industry: "SaaS", revenue: "$10M–$50M", employees: 200, location: "San Francisco, CA", icpScore: 78, isWatched: true },
  { id: "icp-013", companyName: "Demandbase", domain: "demandbase.com", industry: "SaaS", revenue: "$50M–$100M", employees: 650, location: "San Francisco, CA", icpScore: 77, isWatched: true },
  { id: "icp-014", companyName: "Apollo.io", domain: "apollo.io", industry: "SaaS", revenue: "$10M–$50M", employees: 450, location: "Remote", icpScore: 76, isWatched: false },
  { id: "icp-015", companyName: "ZoomInfo", domain: "zoominfo.com", industry: "SaaS", revenue: "$100M+", employees: 3000, location: "Vancouver, WA", icpScore: 74, isWatched: false },
  { id: "icp-016", companyName: "Drift", domain: "drift.com", industry: "SaaS", revenue: "$50M–$100M", employees: 500, location: "Boston, MA", icpScore: 73, isWatched: false },
  { id: "icp-017", companyName: "Intercom", domain: "intercom.com", industry: "SaaS", revenue: "$100M+", employees: 900, location: "San Francisco, CA", icpScore: 71, isWatched: false },
  { id: "icp-018", companyName: "HubSpot", domain: "hubspot.com", industry: "SaaS", revenue: "$100M+", employees: 7000, location: "Cambridge, MA", icpScore: 69, isWatched: false },
  { id: "icp-019", companyName: "Gainsight", domain: "gainsight.com", industry: "SaaS", revenue: "$50M–$100M", employees: 800, location: "San Francisco, CA", icpScore: 67, isWatched: false },
  { id: "icp-020", companyName: "Pendo", domain: "pendo.io", industry: "SaaS", revenue: "$10M–$50M", employees: 400, location: "Raleigh, NC", icpScore: 65, isWatched: false },
  { id: "icp-021", companyName: "Mixpanel", domain: "mixpanel.com", industry: "SaaS", revenue: "$10M–$50M", employees: 350, location: "San Francisco, CA", icpScore: 63, isWatched: false },
  { id: "icp-022", companyName: "Segment", domain: "segment.com", industry: "SaaS", revenue: "$50M–$100M", employees: 600, location: "San Francisco, CA", icpScore: 61, isWatched: false },
  { id: "icp-023", companyName: "Amplitude", domain: "amplitude.com", industry: "SaaS", revenue: "$50M–$100M", employees: 750, location: "San Francisco, CA", icpScore: 58, isWatched: false },
  { id: "icp-024", companyName: "Heap", domain: "heap.io", industry: "SaaS", revenue: "$10M–$50M", employees: 250, location: "San Francisco, CA", icpScore: 54, isWatched: false },
  { id: "icp-025", companyName: "FullStory", domain: "fullstory.com", industry: "SaaS", revenue: "$10M–$50M", employees: 320, location: "Atlanta, GA", icpScore: 51, isWatched: false },
];

// ---------------------------------------------------------------------------
// MOCK_PLAYBOOKS
// ---------------------------------------------------------------------------

export const MOCK_PLAYBOOKS: Record<string, PlaybookData> = {
  "acc-salesloft": {
    accountId: "acc-salesloft",
    accountName: "Salesloft",
    status: "Acting Now",
    version: 4,
    dealValue: "$240K",
    dealStage: "Proposal",
    sourceMeeting: "Technical deep dive · Jun 21",
    thesis:
      "Salesloft is evaluating modern sales co-pilot tooling because their new VP of Sales Engineering is leading a GTM tooling refresh within their first 90 days. Internal sentiment is that existing account planning artifacts in SFDC are stale by the time sellers walk into a call.\n\nThis deal ties to two business initiatives: a sales-eng productivity push and a broader AE ramp-time program owned by the CRO. The pilot scope sits cleanly under the VP SE's mandate, which keeps the decision local and fast for v1.\n\nThis is winnable because we have an active champion in Sarah Kim, a concrete pilot scope, and a budget window that aligns with Q3. The main thing to defend is timing — competing Salesforce work could pull attention if we slip past July.",
    summary: [
      "Salesloft is evaluating a modern sales co-pilot to land a 12-seat pilot in sales engineering, with a path to a 60-seat AE rollout by Q4.",
      "Champion Sarah Kim (Director, Sales Eng) is actively socializing internally; new VP of SE joining in 30 days is the tailwind.",
      "Security sign-off with Angela on EU data residency is the main gating factor — everything else has a clear path to a Jul 30 close.",
      "Economic buyer David (CRO) hasn't joined a live call yet; champion-led intro is the next big unlock.",
      "Competing Salesforce revamp is the biggest external risk on budget; positioning as additive (not competitive) is working so far.",
    ],
    successCriteria: [
      "Pilot team activated within 2 weeks of contract; > 70% weekly active sellers.",
      "Measurable ramp-time lift on the sales-eng cohort within 60 days.",
      "Documented expansion plan signed off by CRO before Q4 planning.",
    ],
    plays: [
      { id: "p1", timeHorizon: "This week", title: "Secure security sign-off with Angela", subtitle: "Unblock DPA review before Jul 5.", assignee: "Ashok", actionLabels: ["Call", "Sync to account plan"] },
      { id: "p2", timeHorizon: "This week", title: "Send security FAQ + redlined DPA", subtitle: "Reduce back-and-forth, set up Angela's review.", assignee: "SE", actionLabels: ["Email sequence", "Sync to account plan"] },
      { id: "p3", timeHorizon: "This month", title: "Champion-led intro to David (CRO)", subtitle: "Validate budget + expansion path beyond pilot.", assignee: "Champion", actionLabels: ["Exec intro", "Sync to account plan"] },
      { id: "p4", timeHorizon: "This month", title: "RevOps governance workshop with Jordan", subtitle: "De-risk internal pushback; align on data flow.", assignee: "SE", actionLabels: ["Workshop", "Sync to account plan"] },
      { id: "p5", timeHorizon: "Before close", title: "Mutual close plan review with Sarah", subtitle: "Lock procurement milestones to Jul 30 close.", assignee: "Ashok", actionLabels: ["Call", "Sync to account plan"] },
      { id: "p6", timeHorizon: "Before close", title: "Expansion narrative for CSM org", subtitle: "Plant seed for land-and-expand in Q4.", assignee: "Ashok", actionLabels: ["Email sequence", "Sync to account plan"] },
    ],
    fitHypotheses: [
      { text: "HubSpot migration creates a native integration window — ideal timing to introduce complementary tooling", priority: "High" },
      { text: "New VP of SE joining in 30 days will want to make a mark fast — champion can leverage this", priority: "High" },
      { text: "12-seat pilot in sales engineering is a low-risk land that expands naturally to 60 AEs", priority: "Med" },
      { text: "Salesloft's own platform focus on seller experience makes them sophisticated buyers", priority: "Low" },
    ],
    landmines: [
      { text: "Salesforce revamp internally may compete for the same budget — position as additive", category: "Budget" },
      { text: "EU data residency requirement adds complexity; Angela (VP Security) is a gating blocker", category: "Technical" },
      { text: "David (CRO) hasn't been in a live call — deal is at risk without economic buyer engagement", category: "Relationship" },
    ],
    talkingPoints: [
      { text: "We natively integrate with HubSpot, which maps directly to their recent migration — zero switching cost in the CRM layer." },
      { text: "The 12-seat SE pilot is designed to prove ROI within 60 days, giving Sarah concrete data before Q4 budget planning." },
      { text: "We're additive to the Salesforce revamp, not competitive — our value is in the co-pilot layer, not the CRM layer." },
    ],
    discoveryQuestions: [
      { text: "How do AEs build account plans today, and where does that artifact live?", actionLabel: "Probe gap", category: "Current Workflow" },
      { text: "What does meeting prep look like for a strategic account this week?", actionLabel: "Probe gap", category: "Current Workflow" },
      { text: "Who reviews account strategy, and how often does it actually change?", actionLabel: "Probe gap", category: "Current Workflow" },
      { text: "What's the manager-to-AE feedback loop on deal strategy today?", actionLabel: "Probe gap", category: "Current Workflow" },
      { text: "Which tools have you tried and rolled back in the last 18 months?", actionLabel: "Surface blockers", category: "Tooling Gaps" },
      { text: "What does your sellers' daily tool surface look like at 9 AM?", actionLabel: "Surface blockers", category: "Tooling Gaps" },
      { text: "Where does SFDC fall short for account-level intelligence?", actionLabel: "Identify pain", category: "Tooling Gaps" },
      { text: "What integrations are non-negotiable for adoption?", actionLabel: "Identify pain", category: "Tooling Gaps" },
      { text: "How are you measuring ramp time and deal velocity today?", actionLabel: "Quantify pain", category: "Economic Impact" },
      { text: "What would a 10% lift in win rate on top accounts unlock?", actionLabel: "Quantify pain", category: "Economic Impact" },
      { text: "Who owns the budget decision, and what's their evaluation bar?", actionLabel: "Map to ROI", category: "Economic Impact" },
      { text: "What's the cost of doing nothing for another two quarters?", actionLabel: "Map to ROI", category: "Economic Impact" },
    ],
    dealObjective: [
      "Land a 12-seat pilot in sales engineering as a wedge for a 60-seat AE rollout.",
      "Close by Jul 30 to align with their Q3 tooling budget cycle.",
      "Success = pilot team adopts in < 2 weeks, with measurable ramp-time lift before expansion conversation.",
    ],
    dealRisks: [
      {
        category: "Contractual",
        risk: "EU data residency / DPA language not yet agreed with Angela (Security).",
        impact: "High",
        probability: "Medium",
        owner: "Ashok",
        mitigation: "Send redlined DPA + security FAQ by Jun 24; schedule 30-min walkthrough with Angela.",
      },
      {
        category: "Political",
        risk: "Economic buyer (David, CRO) has not joined a live call yet.",
        impact: "High",
        probability: "Medium",
        owner: "Sarah + Ashok",
        mitigation: "Champion-led intro call before Jul 5; pre-brief David with a 1-pager.",
      },
      {
        category: "Timing",
        risk: "Procurement typically takes 3 weeks once redlines are settled; risks slipping past Jul 30.",
        impact: "Medium",
        probability: "Medium",
        owner: "Ashok",
        mitigation: "Start procurement intake in parallel with security review; pre-fill vendor forms.",
      },
      {
        category: "Technical",
        risk: "Competing Salesforce revamp could absorb tooling budget this quarter.",
        impact: "High",
        probability: "Low",
        owner: "Sarah",
        mitigation: "Position pilot as additive to SFDC; share ROI delta vs Salesforce-only plan.",
      },
      {
        category: "Political",
        risk: "RevOps (Jordan) skeptical of yet another seller tool.",
        impact: "Medium",
        probability: "Medium",
        owner: "SE",
        mitigation: "Workshop with Jordan focused on data flow + governance; offer pilot read-only mode.",
      },
    ],
    overallRisk: "Medium",
    objections: [
      {
        tag: "Data residency",
        text: "All EU customer data is processed in eu-west-1 with no cross-region transfer. We're happy to share the architecture diagram and updated DPA language ahead of Angela's review.",
        documentLabel: "Security one-pager",
      },
      {
        tag: "Yet another tool",
        text: "We embed in SFDC and Gong, so sellers don't change surface. Pilot can start read-only — zero workflow disruption for the first 30 days.",
        documentLabel: "Integration map",
      },
      {
        tag: "Budget overlap with SFDC revamp",
        text: "We're additive, not competitive. Most customers see ROI inside one quarter on AE ramp alone, which usually frees the SFDC budget conversation rather than competing with it.",
        documentLabel: "ROI calculator",
      },
    ],
    versions: [
      { version: 1, generatedAt: daysAgo(10) },
      { version: 2, generatedAt: daysAgo(6), sourceMeeting: "Discovery call · May 11" },
      { version: 3, generatedAt: daysAgo(3), sourceMeeting: "Demo · May 14" },
      { version: 4, generatedAt: daysAgo(0), sourceMeeting: "Technical deep dive · Jun 21" },
    ],
    nextActions: [
      { id: "na-sl-001", text: "Send redlined DPA to Angela's legal team by Jun 25", due: daysAgo(-3), done: false },
      { id: "na-sl-002", text: "Draft security FAQ addressing EU data residency concerns", due: daysAgo(-2), done: false },
      { id: "na-sl-003", text: "Ask Sarah to schedule champion-led intro with David (CRO)", due: daysAgo(-5), done: false },
      { id: "na-sl-004", text: "Send pilot success metrics template to Sarah", due: daysAgo(-1), done: true },
    ],
    timeline: [
      { date: daysAgo(10), event: "Account added to watchlist", type: "system" },
      { date: daysAgo(8), event: "Tech change signal: Migrated from Marketo to HubSpot", type: "system" },
      { date: daysAgo(6), event: "Initial outreach to Sarah Kim — positive response", type: "email" },
      { date: daysAgo(3), event: "Discovery call with Sarah Kim and Jordan Patel (RevOps)", type: "meeting" },
      { date: daysAgo(1), event: "Technical deep dive with Angela Wu (Security) and SE team", type: "meeting" },
      { date: daysAgo(0), event: "Playbook v4 generated post technical deep dive", type: "system" },
    ],
    stakeholders: [
      { id: "sh-sl-001", name: "Sarah Kim", title: "Director, Sales Engineering", role: "Champion", sentiment: "positive", lastActiveDaysAgo: 3 },
      { id: "sh-sl-002", name: "David Chen", title: "CRO", role: "Economic Buyer", sentiment: "unknown", lastActiveDaysAgo: 12 },
      { id: "sh-sl-003", name: "Jordan Patel", title: "Head of RevOps", role: "Influencer", sentiment: "neutral", lastActiveDaysAgo: 5 },
      { id: "sh-sl-004", name: "Angela Wu", title: "VP of Security", role: "Blocker", sentiment: "negative", lastActiveDaysAgo: 20 },
    ],
    generatedAt: daysAgo(0),
  },

  "acc-lattice": {
    accountId: "acc-lattice",
    accountName: "Lattice",
    status: "Active",
    version: 1,
    thesis:
      "Lattice just closed a $50M Series D and hired a new VP of Sales Engineering from Snowflake. New leaders with fresh budget consistently rebuild their pre-sales and GTM stack within 90 days. The timing is ideal to lead with a technical value story backed by their Snowflake-native workflow.",
    summary: [
      "New $50M Series D and VP of SE hire from Snowflake — strong tailwind for a tech-forward co-pilot pitch.",
      "Marcus Chen (VP SE, ex-Snowflake) is the likely champion; he'll want to put his stamp on the pre-sales stack within 60 days of joining.",
      "No existing relationship yet — first outreach needs to be warm, Snowflake-native, and timed to his ramp window.",
      "Series D budget is unlocked but CFO sign-off is required for new enterprise tools; keep pilot scope under VP SE mandate.",
    ],
    successCriteria: [
      "Discovery call booked with Marcus Chen within 14 days of outreach.",
      "Pilot scoped and agreed within 60 days of first call.",
      "Expansion to AE org signed off by CRO before Q4 planning.",
    ],
    plays: [
      { id: "lp1", timeHorizon: "This week", title: "Send personalized intro to Marcus Chen", subtitle: "Reference Snowflake background — warm the relationship before the ask.", assignee: "AE", actionLabels: ["Email sequence", "Sync to account plan"] },
      { id: "lp2", timeHorizon: "This week", title: "Prepare Lattice-specific one-pager", subtitle: "Series D + Snowflake angle; keep it under 1 page.", assignee: "SE", actionLabels: ["Asset", "Sync to account plan"] },
      { id: "lp3", timeHorizon: "This month", title: "Book discovery call with Marcus", subtitle: "Qualify pilot scope and SE team pain before any demo.", assignee: "AE", actionLabels: ["Call", "Sync to account plan"] },
      { id: "lp4", timeHorizon: "Before close", title: "Present pilot success metrics to Sarah Goldstein (CRO)", subtitle: "Lock expansion narrative before Q4 budget cycle.", assignee: "Ashok", actionLabels: ["Exec intro", "Sync to account plan"] },
    ],
    fitHypotheses: [
      { text: "Their new VP of SE will want a modern demo and POC workflow within 60 days of joining", priority: "High" },
      { text: "Series D budget will unlock enterprise tooling decisions that were blocked before", priority: "High" },
      { text: "Their existing pre-sales tooling is likely 2+ years old given rapid headcount growth", priority: "Med" },
      { text: "HR-adjacent data workflows align with their People Management platform direction", priority: "Low" },
    ],
    landmines: [
      { text: "They may have a vendor locked in through existing Series C commitments", category: "Contractual" },
      { text: "New VP of SE is still building trust internally — avoid deals that need CFO sign-off in Q1", category: "Timing" },
      { text: "Snowflake partnership could create conflict if we compete on data layer", category: "Technical" },
    ],
    talkingPoints: [
      { text: "We natively integrate with Snowflake, which maps directly to their new SE leader's background and comfort zone." },
      { text: "Lattice's current growth rate of 40%+ YoY means their ops complexity is outpacing their current toolset." },
      { text: "Companies at Series D typically hit an inflection point where point solutions create more friction than value." },
    ],
    discoveryQuestions: [
      { text: "What does your current pre-sales workflow look like from opportunity to technical win?", actionLabel: "Probe gap", category: "Process" },
      { text: "How are you measuring the efficiency of your SE team today?", actionLabel: "Quantify pain", category: "Metrics" },
      { text: "What was the trigger for bringing in a new VP of SE at this stage?", actionLabel: "Understand urgency", category: "Leadership" },
      { text: "What does the ideal state look like for your GTM stack 12 months from now?", actionLabel: "Align vision", category: "Strategy" },
    ],
    dealObjective: [
      "Land a discovery meeting with the new VP of Sales Engineering within 30 days of their start date.",
      "Establish a pilot scope tied to their SE team productivity initiative.",
      "Expand to AE org once pilot demonstrates ramp-time improvement.",
    ],
    versions: [
      { version: 1, generatedAt: daysAgo(1) },
    ],
    nextActions: [
      { id: "na-001", text: "Send personalized intro email to new VP of Sales Engineering referencing Snowflake background", due: daysAgo(-2), done: false },
      { id: "na-002", text: "Request 20-min discovery call via LinkedIn (mutual connection exists)", due: daysAgo(-5), done: false },
      { id: "na-003", text: "Prepare Lattice-specific one-pager with Series D and Snowflake angle", due: daysAgo(-3), done: true },
      { id: "na-004", text: "Loop in AE to co-own the account and align on messaging", due: daysAgo(-7), done: false },
    ],
    timeline: [
      { date: daysAgo(14), event: "Account added to watchlist", type: "system" },
      { date: daysAgo(3), event: "Leadership change signal detected: new VP of SE hired", type: "system" },
      { date: daysAgo(1), event: "New funding signal: $50M Series D confirmed", type: "system" },
      { date: daysAgo(1), event: "Playbook generated", type: "system" },
    ],
    stakeholders: [
      { id: "sh-001", name: "Marcus Chen", title: "VP of Sales Engineering", role: "Champion", sentiment: "unknown", lastActiveDaysAgo: 3 },
      { id: "sh-002", name: "Sarah Goldstein", title: "CRO", role: "Economic Buyer", sentiment: "neutral", lastActiveDaysAgo: 12 },
      { id: "sh-003", name: "David Park", title: "Head of RevOps", role: "Influencer", sentiment: "positive", lastActiveDaysAgo: 5 },
      { id: "sh-004", name: "Priya Nair", title: "VP of Engineering", role: "Blocker", sentiment: "negative", lastActiveDaysAgo: 20 },
    ],
    generatedAt: daysAgo(1),
  },

  "acc-qualified": {
    accountId: "acc-qualified",
    accountName: "Qualified",
    status: "Going Cold",
    version: 1,
    thesis:
      "Qualified brought in a new CRO from Salesforce and simultaneously raised $95M in growth equity. The combination of fresh executive leadership and significant capital creates a perfect storm for vendor re-evaluation. Lead with pipeline efficiency and Salesforce ecosystem fit.",
    summary: [
      "New CRO James Whitfield (ex-Salesforce) + $95M growth equity creates a prime re-evaluation window for the full GTM stack.",
      "Anika Sharma (VP RevOps) is a warm champion — pipeline efficiency messaging resonated in initial outreach.",
      "James hasn't joined a live call yet; champion-led intro is the next critical unlock before the 90-day window closes.",
      "Internal political dynamics post-funding are a timing risk — procurement could take 30-60 extra days once started.",
    ],
    successCriteria: [
      "CRO intro call booked via Anika within 30 days.",
      "Pilot scoped and tied to pipeline efficiency metrics the CRO owns.",
      "ROI case signed off before end of Q3 budget window.",
    ],
    plays: [
      { id: "qp1", timeHorizon: "This week", title: "Send exec-level outreach referencing Pipeline Cloud expansion", subtitle: "Position as complementary, not competitive.", assignee: "AE", actionLabels: ["Email sequence", "Sync to account plan"] },
      { id: "qp2", timeHorizon: "This month", title: "Champion-led intro to James Whitfield (CRO)", subtitle: "Validate budget and expansion path before committing to a full pilot.", assignee: "Champion", actionLabels: ["Exec intro", "Sync to account plan"] },
      { id: "qp3", timeHorizon: "Before close", title: "Mutual close plan review with Anika", subtitle: "Lock procurement milestones and align on Q3 deadline.", assignee: "Ashok", actionLabels: ["Call", "Sync to account plan"] },
    ],
    fitHypotheses: [
      { text: "Salesforce-background CRO will gravitate toward tools with deep Salesforce integration", priority: "High" },
      { text: "Growth equity mandate means they need to show ROI metrics fast — we can help instrumentalize that", priority: "High" },
      { text: "Their Pipeline Cloud expansion means they need complementary data infrastructure", priority: "Med" },
      { text: "Mid-stage growth means they are starting to feel the pain of manual RevOps work", priority: "Med" },
    ],
    landmines: [
      { text: "New CRO may have preferred vendors from Salesforce — research his past stack before first call", category: "Relationship" },
      { text: "Internal political dynamics post-funding can slow procurement by 30-60 days", category: "Timing" },
      { text: "They compete directly with some of our existing customers — handle carefully", category: "Commercial" },
    ],
    talkingPoints: [
      { text: "Our Salesforce-native architecture means zero switching cost in the CRM data layer — ideal for a Salesforce-background CRO." },
      { text: "Post-growth equity, investors expect pipeline efficiency metrics within 2 quarters — we accelerate that reporting." },
      { text: "Qualified's Pipeline Cloud and our platform are complementary, not competitive — we plug into their motion." },
    ],
    discoveryQuestions: [
      { text: "What metrics will the new CRO be evaluated on in the first 90 days?", actionLabel: "Map to ROI", category: "Leadership" },
      { text: "How are you currently tracking pipeline conversion rates by segment?", actionLabel: "Find gap", category: "Metrics" },
      { text: "What does your current Salesforce data hygiene process look like?", actionLabel: "Identify pain", category: "Technical" },
      { text: "Are there any tooling decisions that were on hold pending this funding round?", actionLabel: "Unlock budget", category: "Budget" },
    ],
    dealObjective: [
      "Secure a first call with the new CRO within their first 60 days.",
      "Position as complementary to Salesforce — not competitive.",
      "Tie ROI story to pipeline efficiency metrics the CRO will be evaluated on.",
    ],
    versions: [
      { version: 1, generatedAt: daysAgo(2) },
    ],
    nextActions: [
      { id: "na-005", text: "Research new CRO's LinkedIn history and past stack at Salesforce", due: daysAgo(-1), done: true },
      { id: "na-006", text: "Draft exec-level outreach email referencing Pipeline Cloud expansion", due: daysAgo(-3), done: false },
      { id: "na-007", text: "Set Google Alert for Qualified + CRO name for real-time signals", due: daysAgo(-1), done: true },
      { id: "na-008", text: "Schedule internal pre-call strategy session with AE and SE", due: daysAgo(-5), done: false },
    ],
    timeline: [
      { date: daysAgo(7), event: "Account added to watchlist", type: "system" },
      { date: daysAgo(9), event: "New funding signal: $95M growth equity raised", type: "system" },
      { date: daysAgo(4), event: "Leadership change signal: new CRO hired from Salesforce", type: "system" },
      { date: daysAgo(4), event: "Discovery email sent to Head of RevOps", type: "email" },
      { date: daysAgo(2), event: "Playbook generated", type: "system" },
    ],
    stakeholders: [
      { id: "sh-005", name: "James Whitfield", title: "Chief Revenue Officer", role: "Economic Buyer", sentiment: "unknown", lastActiveDaysAgo: 4 },
      { id: "sh-006", name: "Anika Sharma", title: "VP of Revenue Operations", role: "Champion", sentiment: "positive", lastActiveDaysAgo: 2 },
      { id: "sh-007", name: "Tom Reyes", title: "Director of Sales Enablement", role: "Influencer", sentiment: "neutral", lastActiveDaysAgo: 8 },
      { id: "sh-008", name: "Lisa Huang", title: "VP of Finance", role: "Economic Buyer", sentiment: "neutral", lastActiveDaysAgo: 15 },
    ],
    generatedAt: daysAgo(2),
  },

  "acc-clari": {
    accountId: "acc-clari",
    accountName: "Clari",
    status: "Closing",
    version: 1,
    thesis:
      "Clari raised a $225M Series F and immediately posted 22 RevOps and data engineering roles. This level of data team hiring at scale indicates they are building or rebuilding internal data infrastructure — creating an ideal entry point for a platform conversation at the infrastructure layer.",
    summary: [
      "$225M Series F and 22 new data roles signal a major infrastructure build-out — ideal moment for a platform conversation.",
      "Kevin Torres (VP Data Engineering) is a warm contact who understands the build-vs-buy tradeoff at scale.",
      "No economic buyer engagement yet — Rachel Kim (CFO) hasn't been briefed; ROI case needs to be airtight before intro.",
      "At $1.6B valuation, procurement will be formal — expect 90+ day cycle once Kevin commits.",
    ],
    successCriteria: [
      "Build-vs-buy ROI presentation delivered to Kevin's team within 2 weeks.",
      "CFO (Rachel Kim) briefed by end of quarter.",
      "90-day proof-of-value scoped and agreed before Series F hiring wave peaks.",
    ],
    plays: [
      { id: "cp1", timeHorizon: "This week", title: "Build Clari-specific ROI model (build vs. buy)", subtitle: "At their scale, the make-vs-buy case is the opening frame.", assignee: "SE", actionLabels: ["Asset", "Sync to account plan"] },
      { id: "cp2", timeHorizon: "This week", title: "Identify hiring manager for data infrastructure roles", subtitle: "Second champion path if Kevin's bandwidth is stretched.", assignee: "AE", actionLabels: ["Research", "Sync to account plan"] },
      { id: "cp3", timeHorizon: "This month", title: "Champion-led warm intro to Rachel Kim (CFO)", subtitle: "Get economic buyer in the loop before formal procurement starts.", assignee: "Champion", actionLabels: ["Exec intro", "Sync to account plan"] },
      { id: "cp4", timeHorizon: "Before close", title: "Formal proposal with enterprise contract terms", subtitle: "Match their procurement formality — legal and security review prep.", assignee: "Ashok", actionLabels: ["Proposal", "Sync to account plan"] },
    ],
    fitHypotheses: [
      { text: "Massive data hiring wave means they need tooling that scales with a growing data org", priority: "High" },
      { text: "Series F capital creates multi-year budget certainty — enterprise contract terms are in play", priority: "High" },
      { text: "Revenue intelligence focus means they are a native buyer of adjacent analytics tooling", priority: "Med" },
      { text: "Their existing data stack may not scale to support the hiring velocity they are planning", priority: "Med" },
    ],
    landmines: [
      { text: "At $1.6B valuation, procurement cycles are formal and slow — expect 90+ day sales cycles", category: "Process" },
      { text: "Internal 'build vs. buy' debate is likely — have ROI data ready", category: "Technical" },
      { text: "Heavy investor scrutiny post-Series F means they will negotiate hard on pricing", category: "Commercial" },
    ],
    talkingPoints: [
      { text: "We compress the time-to-value for data infrastructure by 60% compared to in-house builds — critical at this hiring pace." },
      { text: "Revenue teams at Clari's scale generate data complexity that requires platform-grade solutions, not scripts." },
      { text: "A $225M raise means they have the budget to do this right the first time rather than patch solutions together." },
    ],
    discoveryQuestions: [
      { text: "What is driving the decision to hire 22 data roles now versus 6 months ago?", actionLabel: "Understand urgency", category: "Strategy" },
      { text: "Is there an internal data platform initiative underway, or are teams working in silos?", actionLabel: "Map architecture", category: "Technical" },
      { text: "How are you currently handling data quality and enrichment across your revenue data?", actionLabel: "Find pain", category: "Process" },
      { text: "What does success look like for the data org 18 months post-funding?", actionLabel: "Align vision", category: "Strategy" },
    ],
    dealObjective: [
      "Open a platform-level conversation with the data infrastructure team.",
      "Demonstrate 60% reduction in time-to-value vs. in-house builds.",
      "Align on a 90-day proof-of-value tied to their Series F hiring wave.",
    ],
    versions: [
      { version: 1, generatedAt: daysAgo(0) },
    ],
    nextActions: [
      { id: "na-009", text: "Identify the hiring manager for the data infrastructure roles on LinkedIn", due: daysAgo(-1), done: false },
      { id: "na-010", text: "Reach out to existing Clari contact in customer network for warm intro", due: daysAgo(-3), done: false },
      { id: "na-011", text: "Build Clari-specific ROI model showing build vs. buy at their scale", due: daysAgo(-5), done: false },
      { id: "na-012", text: "Add Clari to ABM sequence in Outreach with funding+hiring angle", due: daysAgo(-2), done: true },
    ],
    timeline: [
      { date: daysAgo(25), event: "Account added to watchlist", type: "system" },
      { date: daysAgo(0), event: "New funding signal: $225M Series F at $1.6B valuation", type: "system" },
      { date: daysAgo(2), event: "Hiring surge signal: 22 RevOps and data roles posted", type: "system" },
      { date: daysAgo(22), event: "Initial discovery email sent to VP of Data", type: "email" },
      { date: daysAgo(18), event: "Discovery call held — no decision maker present", type: "meeting" },
      { date: daysAgo(0), event: "Playbook regenerated post-funding news", type: "system" },
    ],
    stakeholders: [
      { id: "sh-009", name: "Kevin Torres", title: "VP of Data Engineering", role: "Champion", sentiment: "positive", lastActiveDaysAgo: 5 },
      { id: "sh-010", name: "Rachel Kim", title: "CFO", role: "Economic Buyer", sentiment: "neutral", lastActiveDaysAgo: 18 },
      { id: "sh-011", name: "Brian Patel", title: "Head of RevOps", role: "Influencer", sentiment: "positive", lastActiveDaysAgo: 3 },
      { id: "sh-012", name: "Michelle Foster", title: "Director of IT Security", role: "Blocker", sentiment: "negative", lastActiveDaysAgo: 10 },
      { id: "sh-013", name: "Jason Wu", title: "Senior Data Architect", role: "Ops", sentiment: "positive", lastActiveDaysAgo: 1 },
    ],
    generatedAt: daysAgo(0),
  },
};

// ---------------------------------------------------------------------------
// MOCK_PLAYBOOK_LIST — summary rows for the Playbook list view
// ---------------------------------------------------------------------------

export const MOCK_PLAYBOOK_LIST: PlaybookListItem[] = [
  {
    id: "pb-lattice",
    accountId: "acc-lattice",
    accountName: "Lattice",
    status: "Active",
    lastUpdated: daysAgo(1),
    nextAction: "Send personalized intro email to new VP of Sales Engineering",
  },
  {
    id: "pb-qualified",
    accountId: "acc-qualified",
    accountName: "Qualified",
    status: "Active",
    lastUpdated: daysAgo(2),
    nextAction: "Draft exec-level outreach email referencing Pipeline Cloud expansion",
  },
  {
    id: "pb-clari",
    accountId: "acc-clari",
    accountName: "Clari",
    status: "Active",
    lastUpdated: daysAgo(0),
    nextAction: "Identify the hiring manager for the data infrastructure roles on LinkedIn",
  },
  {
    id: "pb-gong",
    accountId: "acc-gong",
    accountName: "Gong",
    status: "Paused",
    lastUpdated: daysAgo(9),
    nextAction: "Re-engage once mid-market launch settles",
  },
  {
    id: "pb-6sense",
    accountId: "acc-6sense",
    accountName: "6sense",
    status: "Active",
    lastUpdated: daysAgo(4),
    nextAction: "Follow up on EMEA expansion with localization angle",
  },
];

// ---------------------------------------------------------------------------
// DEMO_ACCOUNTS — shown when user has no real watched accounts
// ---------------------------------------------------------------------------

export const DEMO_ACCOUNTS: WatchlistAccount[] = [
  {
    id: "demo-acc-1",
    accountName: "Gong",
    domain: "gong.io",
    industry: "SaaS",
    revenue: "$100M+",
    employees: "1001–5000",
    location: "San Francisco, CA",
    addedAt: daysAgo(10),
    monitoredSignals: ["hiring_surge", "expansion", "new_funding"],
    signals: [
      {
        id: "demo-sig-1",
        type: "hiring_surge",
        summary: "Gong posted 34 new sales and engineering roles this week, signaling a significant GTM ramp ahead of their annual conference.",
        detectedAt: daysAgo(2),
        source: "LinkedIn Jobs",
        seenAt: null,
        accountId: "demo-acc-1",
      },
      {
        id: "demo-sig-2",
        type: "expansion",
        summary: "Gong launched a new mid-market product tier, opening a segment they previously left to competitors.",
        detectedAt: daysAgo(7),
        source: "Gong Blog",
        seenAt: daysAgo(6),
        accountId: "demo-acc-1",
      },
    ],
    intentScore: 82,
    intentLabel: "Hot",
  },
  {
    id: "demo-acc-2",
    accountName: "Outreach",
    domain: "outreach.io",
    industry: "SaaS",
    revenue: "$100M+",
    employees: "1001–5000",
    location: "Seattle, WA",
    addedAt: daysAgo(15),
    monitoredSignals: ["intent_surge", "tech_change"],
    signals: [
      {
        id: "demo-sig-3",
        type: "intent_surge",
        summary: "Outreach's team is researching 'revenue intelligence' and 'conversation analytics' heavily — a buying signal for complementary tooling.",
        detectedAt: daysAgo(3),
        source: "Bombora",
        seenAt: null,
        accountId: "demo-acc-2",
      },
    ],
    intentScore: 61,
    intentLabel: "Warm",
  },
  {
    id: "demo-acc-3",
    accountName: "Clari",
    domain: "clari.com",
    industry: "SaaS",
    revenue: "$100M+",
    employees: "501–1000",
    location: "Sunnyvale, CA",
    addedAt: daysAgo(20),
    monitoredSignals: ["new_funding", "hiring_surge"],
    signals: [
      {
        id: "demo-sig-4",
        type: "new_funding",
        summary: "Clari raised $225M Series F at a $1.6B valuation — one of the largest revenue intelligence funding rounds on record.",
        detectedAt: daysAgo(0),
        source: "TechCrunch",
        seenAt: null,
        accountId: "demo-acc-3",
      },
      {
        id: "demo-sig-5",
        type: "hiring_surge",
        summary: "Clari posted 22 RevOps and data engineering roles this week, indicating a major platform build-out.",
        detectedAt: daysAgo(2),
        source: "LinkedIn Jobs",
        seenAt: null,
        accountId: "demo-acc-3",
      },
    ],
    intentScore: 88,
    intentLabel: "Hot",
  },
  {
    id: "demo-acc-4",
    accountName: "Demandbase",
    domain: "demandbase.com",
    industry: "SaaS",
    revenue: "$50M–$100M",
    employees: "501–1000",
    location: "San Francisco, CA",
    addedAt: daysAgo(8),
    monitoredSignals: ["tech_change"],
    signals: [
      {
        id: "demo-sig-6",
        type: "tech_change",
        summary: "Demandbase migrated from Salesforce to HubSpot CRM — a major platform change that creates a window for complementary ABM tooling integrations.",
        detectedAt: daysAgo(7),
        source: "BuiltWith",
        seenAt: daysAgo(6),
        accountId: "demo-acc-4",
      },
    ],
    intentScore: 53,
    intentLabel: "Warm",
  },
  {
    id: "demo-acc-5",
    accountName: "Bombora",
    domain: "bombora.com",
    industry: "SaaS",
    revenue: "$10M–$50M",
    employees: "101–500",
    location: "New York, NY",
    addedAt: daysAgo(25),
    monitoredSignals: ["leadership_change", "hiring_surge"],
    signals: [
      {
        id: "demo-sig-7",
        type: "leadership_change",
        summary: "Bombora promoted their VP of Product to Chief Product Officer — a title change that typically signals a product-led growth pivot.",
        detectedAt: daysAgo(11),
        source: "LinkedIn",
        seenAt: daysAgo(10),
        accountId: "demo-acc-5",
      },
    ],
    intentScore: 38,
    intentLabel: "Cold",
  },
];

// ---------------------------------------------------------------------------
// MOCK_ACCOUNT_DETAILS — rich per-account data for the Account View page
// ---------------------------------------------------------------------------

export const MOCK_ACCOUNT_DETAILS: Record<string, AccountDetails> = {
  "acc-lattice": {
    accountId: "acc-lattice",
    dealStage: "Proposal",
    dealValue: "$240K",
    targetCloseDate: "Jul 30",
    champion: "Marcus Chen · VP Sales Engineering",
    playbookVersion: 4,
    updatedLabel: "2 hours ago",
    accountSummaryWithMeetings: "Lattice is moving steadily through proposal. Marcus Chen (VP Sales Engineering) has emerged as a strong champion after the pilot-scoping session on Jun 17, and the Jun 21 technical deep dive confirmed product fit with the sales-eng workflow. The main open thread is EU data residency raised by Priya in engineering security, which is now blocking on a redlined DPA we owe by Jun 24.\n\nMomentum is positive but conditional on getting the security review cleared before Sarah (CRO) is brought in for the economic buyer conversation. Procurement timing aligns with a Jul 30 close if the next two touchpoints land cleanly.",
    accountSummaryWithoutMeetings: "This becomes an auto-generated account brief: recent funding rounds, hiring patterns in the relevant buying teams, product launches, leadership changes, and other public triggers that map to this seller's ICP and value proposition.\n\nBefore first contact this is a business brief; after meetings exist, the card switches to the running narrative of the deal so far.",
    meetings: [
      {
        id: "m-lat-1",
        date: "Jun 21",
        durationMin: 45,
        meetingType: "Technical deep dive",
        title: "Call · Sales engineering + security",
        attendees: "Marcus Chen (VP Sales Eng), Priya Nair (VP Eng), you + solutions engineer",
        tags: [
          { label: "Objection · data residency", color: "rose" },
          { label: "Next step refined", color: "green" },
        ],
        summary: "Walked through the reference architecture and answered tenancy questions. Security raised EU data residency as a blocker that needs DPA language tightened. Agreed to share redlined DPA and a security FAQ before Priya's review.",
      },
      {
        id: "m-lat-2",
        date: "Jun 17",
        durationMin: 30,
        meetingType: "Pilot scoping",
        title: "Call · Pilot team alignment",
        attendees: "Marcus Chen, Ashok, Mia (CS)",
        tags: [
          { label: "Pilot scoped", color: "indigo" },
          { label: "Success metrics agreed", color: "green" },
        ],
        summary: "Confirmed the initial pilot team (12 seats, sales-eng org) and three success metrics tied to ramp time. Marcus will socialise with Sarah (CRO) and confirm budget owner this week.",
      },
      {
        id: "m-lat-3",
        date: "Jun 10",
        durationMin: 60,
        meetingType: "Discovery",
        title: "Call · Use cases + workflow walkthrough",
        attendees: "Marcus Chen, two AE managers, you",
        tags: [
          { label: "Champion engaged", color: "green" },
          { label: "Procurement timeline shared", color: "indigo" },
        ],
        summary: "Strong fit on the AE coaching workflow. Marcus is willing to champion internally and flagged procurement typically takes 3 weeks once redlines are settled. No major objections raised in this session.",
      },
    ],
    dealSnapshot: {
      health: "On track",
      amount: "$240,000 ARR",
      stageProbability: "65% · Proposal",
      nextMilestone: "Security sign-off by Jul 5",
      meetingsLogged: 9,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner), Tony (SE), Mia (CS)",
      pathLabel: "Green path to close",
    },
    mutualActionPlan: [
      { id: "map-lat-1", text: "Confirm pilot team and success metrics with Marcus.", assignee: "Ashok", status: "done", dateLabel: "Jun 17" },
      { id: "map-lat-2", text: "Run technical deep dive with SE + engineering security team.", assignee: "Tony", status: "done", dateLabel: "Jun 21" },
      { id: "map-lat-3", text: "Share redlined DPA and security FAQ with Priya.", assignee: "Ashok", status: "due", dateLabel: "Jun 24" },
      { id: "map-lat-4", text: "Align with Sarah (CRO) on pilot scope and expansion path.", assignee: "Marcus + Ashok", status: "target", dateLabel: "before Jul 5" },
    ],
  },

  "acc-salesloft": {
    accountId: "acc-salesloft",
    dealStage: "Proposal",
    dealValue: "$240K",
    targetCloseDate: "Jul 30",
    champion: "Sarah Kim · Director, Sales Engineering",
    playbookVersion: 4,
    updatedLabel: "2 hours ago",
    accountSummaryWithMeetings: "Salesloft is moving steadily through proposal. Sarah Kim (Director, Sales Engineering) has emerged as a strong champion after the pilot-scoping session on Jun 17, and the Jun 21 technical deep dive confirmed product fit with the sales-eng workflow. The main open thread is EU data residency raised by Angela in security, which is now blocking on a redlined DPA we owe by Jun 24.\n\nMomentum is positive but conditional on getting Angela comfortable before David (CRO) is brought in. Procurement timing aligns with a Jul 30 close if the next two touchpoints land cleanly.",
    accountSummaryWithoutMeetings: "This becomes an auto-generated account brief: recent funding rounds, hiring patterns in the relevant buying teams, product launches, leadership changes, and other public triggers that map to this seller's ICP and value proposition.\n\nBefore first contact this is a business brief; after meetings exist, the card switches to the running narrative of the deal so far.",
    meetings: [
      {
        id: "m-sl-1",
        date: "Jun 21",
        durationMin: 45,
        meetingType: "Technical deep dive",
        title: "Call · Sales engineering + security",
        attendees: "Sarah Kim (Director, Sales Eng), DevSecOps lead, you + solutions engineer",
        tags: [
          { label: "Objection · data residency", color: "rose" },
          { label: "Next step refined", color: "green" },
        ],
        summary: "Walked through the reference architecture and answered tenancy questions. Security raised EU data residency as a blocker that needs DPA language tightened. Agreed to share redlined DPA and a security FAQ before Angela's review.",
      },
      {
        id: "m-sl-2",
        date: "Jun 17",
        durationMin: 30,
        meetingType: "Pilot scoping",
        title: "Call · Pilot team alignment",
        attendees: "Sarah Kim, Ashok, Mia (CS)",
        tags: [
          { label: "Pilot scoped", color: "indigo" },
          { label: "Success metrics agreed", color: "green" },
        ],
        summary: "Confirmed the initial pilot team (12 seats, sales-eng org) and three success metrics tied to ramp time. Sarah will socialise with David (CRO) and confirm budget owner this week.",
      },
      {
        id: "m-sl-3",
        date: "Jun 10",
        durationMin: 60,
        meetingType: "Discovery",
        title: "Call · Use cases + workflow walkthrough",
        attendees: "Sarah Kim, two AE managers, you",
        tags: [
          { label: "Champion engaged", color: "green" },
          { label: "Procurement timeline shared", color: "indigo" },
        ],
        summary: "Strong fit on the AE coaching workflow. Sarah is willing to champion internally and flagged procurement typically takes 3 weeks once redlines are settled. No major objections raised in this session.",
      },
    ],
    dealSnapshot: {
      health: "On track",
      amount: "$240,000 ARR",
      stageProbability: "65% · Proposal",
      nextMilestone: "Security sign-off by Jul 5",
      meetingsLogged: 9,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner), Tony (SE), Mia (CS)",
      pathLabel: "Green path to close",
    },
    mutualActionPlan: [
      { id: "map-sl-1", text: "Confirm pilot team and success metrics with Sarah.", assignee: "Ashok", status: "done", dateLabel: "Jun 17" },
      { id: "map-sl-2", text: "Run technical deep dive with SE + security team.", assignee: "Tony", status: "done", dateLabel: "Jun 21" },
      { id: "map-sl-3", text: "Share redlined DPA and security FAQ with Angela.", assignee: "Ashok", status: "due", dateLabel: "Jun 24" },
      { id: "map-sl-4", text: "Align with David (CRO) on pilot scope and expansion path.", assignee: "Sarah + Ashok", status: "target", dateLabel: "before Jul 5" },
    ],
  },

  "acc-qualified": {
    accountId: "acc-qualified",
    dealStage: "Discovery",
    dealValue: "$180K",
    targetCloseDate: "Aug 15",
    champion: "Anika Sharma · VP Revenue Operations",
    playbookVersion: 2,
    updatedLabel: "1 day ago",
    accountSummaryWithoutMeetings: "Qualified raised $95M in growth equity and hired a new CRO from Salesforce. This is an auto-generated brief based on public signals — schedule the first call to begin building the deal narrative.\n\nKey angle: the new CRO's Salesforce background makes them a natural buyer of native Salesforce integrations. Target Anika in RevOps as the champion path.",
    meetings: [],
    dealSnapshot: {
      health: "At risk",
      amount: "$180,000 ARR",
      stageProbability: "40% · Discovery",
      nextMilestone: "First call with CRO",
      meetingsLogged: 0,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner), Tony (SE)",
    },
    mutualActionPlan: [
      { id: "map-q-1", text: "Send exec-level intro email to James Whitfield (CRO).", assignee: "Ashok", status: "due", dateLabel: "Jun 25" },
      { id: "map-q-2", text: "Schedule first discovery call with Anika Sharma.", assignee: "Ashok", status: "target", dateLabel: "before Jul 1" },
    ],
  },

  "acc-gong": {
    accountId: "acc-gong",
    dealStage: "Evaluation",
    dealValue: "$320K",
    targetCloseDate: "Sep 30",
    champion: "Priya Mehta · VP Revenue Operations",
    playbookVersion: 3,
    updatedLabel: "3 hours ago",
    accountSummaryWithMeetings: "Gong is actively evaluating alternatives to their current stack after launching a mid-market product tier and opening 34 GTM roles. Priya (VP RevOps) is driving the evaluation and has strong internal credibility — she greenlit the shortlist.\n\nThe main risk is a competing internal tool build backed by their engineering team. Our angle is speed-to-value and breadth of integrations. Technical validation call is the critical next step before the Q3 decision window closes.",
    accountSummaryWithoutMeetings: "Gong is in aggressive GTM expansion mode — 34 new roles posted and a new mid-market tier launched this month. This is an ideal entry point for a conversation about infrastructure that scales with their growth.\n\nTarget Priya in RevOps as the champion path. The hiring surge signal suggests budget is unlocked and decisions are moving fast.",
    meetings: [
      {
        id: "m-gong-1",
        date: "Jun 19",
        durationMin: 45,
        meetingType: "Evaluation kickoff",
        title: "Call · Stack evaluation + requirements",
        attendees: "Priya Mehta (VP RevOps), two RevOps analysts, you",
        tags: [
          { label: "Shortlisted", color: "green" },
          { label: "Technical validation required", color: "amber" },
        ],
        summary: "Priya confirmed we're on the shortlist alongside one internal build option. Requirements are clear: Salesforce-native, real-time enrichment, and sub-200ms API response. She wants a technical validation session with her data architect before recommending to the CRO.",
      },
      {
        id: "m-gong-2",
        date: "Jun 12",
        durationMin: 30,
        meetingType: "Discovery",
        title: "Call · Use case + integration walkthrough",
        attendees: "Priya Mehta, Ashok",
        tags: [
          { label: "Champion engaged", color: "green" },
          { label: "Budget confirmed", color: "indigo" },
        ],
        summary: "Strong discovery call. Priya confirmed Q3 budget is allocated and the decision will be made by the CRO before Sep 30. She's willing to champion internally if technical validation goes well.",
      },
    ],
    dealSnapshot: {
      health: "On track",
      amount: "$320,000 ARR",
      stageProbability: "55% · Evaluation",
      nextMilestone: "Technical validation with data architect",
      meetingsLogged: 6,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner), Tony (SE), Lena (SE)",
      pathLabel: "Green path to close",
    },
    mutualActionPlan: [
      { id: "map-gong-1", text: "Send API performance benchmarks to Priya's data architect.", assignee: "Tony", status: "due", dateLabel: "Jun 24" },
      { id: "map-gong-2", text: "Schedule technical validation session with data architect.", assignee: "Ashok", status: "due", dateLabel: "Jun 27" },
      { id: "map-gong-3", text: "Deliver ROI model comparing build vs. buy at Gong's scale.", assignee: "Ashok", status: "target", dateLabel: "before Jul 10" },
      { id: "map-gong-4", text: "CRO alignment call after technical sign-off.", assignee: "Priya + Ashok", status: "target", dateLabel: "before Aug 1" },
    ],
  },

  "acc-outreach": {
    accountId: "acc-outreach",
    dealStage: "Discovery",
    dealValue: "$210K",
    targetCloseDate: "Oct 15",
    champion: "Rachel Torres · Director of Sales Ops",
    playbookVersion: 1,
    updatedLabel: "5 hours ago",
    accountSummaryWithMeetings: "Outreach recently replaced Drift with Qualified for pipeline and is now evaluating their broader GTM stack. Rachel in Sales Ops is the internal driver — she has sponsorship from the CRO to run this evaluation.\n\nThe tech change signal (Drift → Qualified) is the entry point. Their openness to vendor consolidation is high right now. First discovery call confirmed budget and timeline — decision by Oct 15.",
    accountSummaryWithoutMeetings: "Outreach replaced Drift with Qualified — a clear signal of active vendor consolidation. This is the ideal moment to position complementary tooling that integrates natively with their evolving stack.\n\nTarget Rachel in Sales Ops as the champion. The intent surge on revenue intelligence topics confirms the buying committee is actively researching.",
    meetings: [
      {
        id: "m-out-1",
        date: "Jun 20",
        durationMin: 30,
        meetingType: "Discovery",
        title: "Call · Current stack + pain points",
        attendees: "Rachel Torres (Director Sales Ops), you",
        tags: [
          { label: "Budget confirmed", color: "indigo" },
          { label: "Oct decision window", color: "amber" },
        ],
        summary: "Rachel confirmed they are evaluating 3 vendors. Budget is $200–250K ARR. Decision timeline is Oct 15 before Q4 planning. She flagged integration complexity as a key evaluation criteria — native Salesforce sync is a must-have.",
      },
    ],
    dealSnapshot: {
      health: "On track",
      amount: "$210,000 ARR",
      stageProbability: "35% · Discovery",
      nextMilestone: "Send integration architecture doc",
      meetingsLogged: 3,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner), Tony (SE)",
    },
    mutualActionPlan: [
      { id: "map-out-1", text: "Send Salesforce-native integration architecture overview to Rachel.", assignee: "Tony", status: "due", dateLabel: "Jun 25" },
      { id: "map-out-2", text: "Schedule deep-dive demo focused on data sync.", assignee: "Ashok", status: "target", dateLabel: "before Jul 5" },
      { id: "map-out-3", text: "Request intro to CRO sponsor for exec alignment.", assignee: "Rachel + Ashok", status: "target", dateLabel: "before Jul 20" },
    ],
  },

  "acc-6sense": {
    accountId: "acc-6sense",
    dealStage: "Prospecting",
    dealValue: "$290K",
    targetCloseDate: "Nov 1",
    champion: "Marcus Webb · Head of Revenue Analytics",
    playbookVersion: 1,
    updatedLabel: "6 hours ago",
    accountSummaryWithoutMeetings: "6sense opened a new EMEA office and is spiking on pipeline generation research — two strong signals of a team scaling their GTM infrastructure. No meetings yet.\n\nBest entry point is Marcus in Revenue Analytics. The EMEA expansion means they need tooling that works across geographies. Our multi-region data coverage is the differentiated angle.",
    meetings: [],
    dealSnapshot: {
      health: "At risk",
      amount: "$290,000 ARR",
      stageProbability: "20% · Prospecting",
      nextMilestone: "First outreach to Marcus Webb",
      meetingsLogged: 0,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner)",
    },
    mutualActionPlan: [
      { id: "map-6s-1", text: "Send personalised outreach to Marcus referencing EMEA expansion.", assignee: "Ashok", status: "due", dateLabel: "Jun 24" },
      { id: "map-6s-2", text: "Request intro through shared connection at G2.", assignee: "Ashok", status: "target", dateLabel: "before Jun 30" },
    ],
  },

  "acc-clari": {
    accountId: "acc-clari",
    dealStage: "Evaluation",
    dealValue: "$450K",
    targetCloseDate: "Sep 15",
    champion: "Kevin Torres · VP Data Engineering",
    playbookVersion: 3,
    updatedLabel: "1 hour ago",
    accountSummaryWithMeetings: "Clari raised $225M Series F and immediately opened 22 data roles — the clearest possible signal of an infrastructure build-out. Kevin (VP Data Engineering) is driving the vendor evaluation and has board-level visibility on this initiative.\n\nThe 'build vs. buy' debate is real. Our strongest angle is compressing their time-to-production by 60% — Kevin responded positively to this framing in the second call. Michelle in IT Security is the main blocker; she needs SOC 2 Type II documentation before signing off.",
    accountSummaryWithoutMeetings: "Clari raised $225M Series F and posted 22 RevOps and data engineering roles. This level of data team hiring at scale indicates a major infrastructure initiative — a platform conversation at the data layer is highly timely.\n\nTarget Kevin in Data Engineering as the champion path.",
    meetings: [
      {
        id: "m-clari-1",
        date: "Jun 18",
        durationMin: 60,
        meetingType: "Technical deep dive",
        title: "Call · Data architecture + integration requirements",
        attendees: "Kevin Torres (VP Data Eng), Jason Wu (Sr Data Architect), you + Tony (SE)",
        tags: [
          { label: "Build vs. buy framing landed", color: "green" },
          { label: "SOC 2 required", color: "rose" },
        ],
        summary: "Strong technical session. Jason walked through their planned architecture — our platform fits cleanly into their data mesh design. Kevin committed to a 30-day POC if we can provide SOC 2 Type II and complete a security review with Michelle. Time-to-production framing resonated strongly.",
      },
      {
        id: "m-clari-2",
        date: "Jun 10",
        durationMin: 45,
        meetingType: "Discovery",
        title: "Call · Data org scale + vendor evaluation criteria",
        attendees: "Kevin Torres, Brian Patel (Head of RevOps), Ashok",
        tags: [
          { label: "Champion engaged", color: "green" },
          { label: "POC pathway agreed", color: "indigo" },
        ],
        summary: "Kevin confirmed the evaluation is Board-sponsored with a Sep 15 decision deadline. Three vendors are being evaluated. Brian in RevOps is aligned and will co-sponsor the recommendation. Budget is confirmed at $400–500K ARR range.",
      },
    ],
    dealSnapshot: {
      health: "On track",
      amount: "$450,000 ARR",
      stageProbability: "60% · Evaluation",
      nextMilestone: "SOC 2 review with Michelle Foster",
      meetingsLogged: 8,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner), Tony (SE), Mia (CS)",
      pathLabel: "Green path to close",
    },
    mutualActionPlan: [
      { id: "map-cl-1", text: "Share SOC 2 Type II documentation with Michelle Foster.", assignee: "Ashok", status: "due", dateLabel: "Jun 24" },
      { id: "map-cl-2", text: "Complete security questionnaire with IT team.", assignee: "Tony", status: "due", dateLabel: "Jun 28" },
      { id: "map-cl-3", text: "Kick off 30-day POC with Jason Wu's data team.", assignee: "Tony + Jason", status: "target", dateLabel: "Jul 5" },
      { id: "map-cl-4", text: "Executive alignment call with Kevin + CFO Rachel Kim.", assignee: "Ashok + Kevin", status: "target", dateLabel: "before Aug 15" },
    ],
  },

  "acc-bombora": {
    accountId: "acc-bombora",
    dealStage: "Prospecting",
    dealValue: "$95K",
    targetCloseDate: "Nov 30",
    updatedLabel: "2 days ago",
    accountSummaryWithoutMeetings: "Bombora promoted their VP of Product to CPO — a title change that typically signals a product-led growth pivot and a broader platform ambition. Their intent score is declining (-14), suggesting the window may be narrowing.\n\nBest angle: reach out to the new CPO with a product-led framing. Bombora as a data provider is a natural buyer of complementary enrichment tooling. Move fast while the leadership transition is fresh.",
    meetings: [],
    dealSnapshot: {
      health: "At risk",
      amount: "$95,000 ARR",
      stageProbability: "15% · Prospecting",
      nextMilestone: "First outreach to new CPO",
      meetingsLogged: 0,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner)",
    },
    mutualActionPlan: [
      { id: "map-bo-1", text: "Research new CPO's background and past stack decisions.", assignee: "Ashok", status: "due", dateLabel: "Jun 25" },
      { id: "map-bo-2", text: "Draft personalised outreach referencing PLG pivot signal.", assignee: "Ashok", status: "target", dateLabel: "before Jun 30" },
    ],
  },

  "acc-clearbit": {
    accountId: "acc-clearbit",
    dealStage: "Prospecting",
    dealValue: "$120K",
    targetCloseDate: "Dec 15",
    updatedLabel: "3 days ago",
    accountSummaryWithoutMeetings: "Clearbit is spiking on intent research for data enrichment alternatives — a clear signal they are evaluating vendors in their own category, which creates a partnership or displacement opportunity.\n\nNo meetings yet. Cold outreach with an intent-data angle is the right opener. Their score is low (31) — prioritise only if bandwidth allows.",
    meetings: [],
    dealSnapshot: {
      health: "At risk",
      amount: "$120,000 ARR",
      stageProbability: "10% · Prospecting",
      nextMilestone: "Cold outreach — data enrichment angle",
      meetingsLogged: 0,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner)",
    },
    mutualActionPlan: [
      { id: "map-cb-1", text: "Send cold outreach referencing intent spike on enrichment alternatives.", assignee: "Ashok", status: "target", dateLabel: "before Jul 5" },
    ],
  },

  "acc-demandbase": {
    accountId: "acc-demandbase",
    dealStage: "Discovery",
    dealValue: "$175K",
    targetCloseDate: "Oct 30",
    champion: "Sophia Park · Director of Marketing Ops",
    playbookVersion: 1,
    updatedLabel: "4 hours ago",
    accountSummaryWithMeetings: "Demandbase switched from Salesforce to HubSpot CRM — a significant tech stack change that opens a native integration conversation. Sophia in Marketing Ops is the internal driver and responded positively to our initial outreach.\n\nFirst call confirmed they are evaluating 2 vendors. The HubSpot migration is recent (30 days) so timing is ideal. Move to demo quickly before the evaluation window closes.",
    accountSummaryWithoutMeetings: "Demandbase switched from Salesforce to HubSpot — the ideal moment to introduce tooling that integrates natively with their new CRM. Their intent data focus makes them a sophisticated buyer.\n\nTarget Sophia in Marketing Ops. The tech change signal is the opener.",
    meetings: [
      {
        id: "m-db-1",
        date: "Jun 16",
        durationMin: 30,
        meetingType: "Discovery",
        title: "Call · HubSpot migration + integration needs",
        attendees: "Sophia Park (Director Marketing Ops), you",
        tags: [
          { label: "Shortlisted", color: "green" },
          { label: "HubSpot-native required", color: "indigo" },
        ],
        summary: "Sophia confirmed they migrated to HubSpot 30 days ago and are now evaluating complementary data tooling. Must-have: native HubSpot sync and real-time enrichment. Two vendors shortlisted — decision by Oct 30. She's willing to champion if demo goes well.",
      },
    ],
    dealSnapshot: {
      health: "On track",
      amount: "$175,000 ARR",
      stageProbability: "45% · Discovery",
      nextMilestone: "Product demo — HubSpot integration focus",
      meetingsLogged: 2,
      meetingsPeriod: "last 30 days",
      team: "You · Ashok (owner), Tony (SE)",
    },
    mutualActionPlan: [
      { id: "map-db-1", text: "Schedule full product demo with HubSpot integration walkthrough.", assignee: "Ashok", status: "due", dateLabel: "Jun 26" },
      { id: "map-db-2", text: "Send HubSpot native connector technical spec to Sophia.", assignee: "Tony", status: "due", dateLabel: "Jun 25" },
      { id: "map-db-3", text: "Get intro to VP of Marketing for exec sponsorship.", assignee: "Sophia + Ashok", status: "target", dateLabel: "before Jul 15" },
    ],
  },
};
