import type { SignalEvent, WatchlistAccount, ICPAccount, PlaybookData, PlaybookListItem } from "./types";

// Helper: ISO date N days ago
function daysAgo(n: number): string {
  const d = new Date("2026-05-17T00:00:00.000Z");
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

// ---------------------------------------------------------------------------
// MOCK_SIGNALS
// ---------------------------------------------------------------------------

export const MOCK_SIGNALS: SignalEvent[] = [
  {
    id: "sig-001",
    type: "new_funding",
    headline: "$50M Series D led by a16z",
    summary: "Round signals aggressive product expansion and a larger 2026 tooling budget. Net-new tier likely.",
    detectedAt: daysAgo(1),
    source: "Crunchbase",
    seenAt: null,
    accountId: "acc-lattice",
  },
  {
    id: "sig-002",
    type: "hiring_surge",
    headline: "34 new GTM & engineering roles",
    summary: "Sales and engineering reqs opened this week — a significant GTM ramp ahead of their annual Celebrate conference.",
    detectedAt: daysAgo(2),
    source: "LinkedIn Jobs",
    seenAt: daysAgo(1),
    accountId: "acc-gong",
  },
  {
    id: "sig-003",
    type: "intent_surge",
    headline: "Heavy research on \"revenue intelligence\"",
    summary: "Outreach team has been researching revenue intelligence and conversation analytics across 14 properties.",
    detectedAt: daysAgo(3),
    source: "Bombora",
    seenAt: null,
    accountId: "acc-outreach",
  },
  {
    id: "sig-004",
    type: "tech_change",
    headline: "Migrated from Marketo to HubSpot",
    summary: "Switch creates a window for complementary tooling that integrates with HubSpot natively.",
    detectedAt: daysAgo(2),
    source: "BuiltWith",
    seenAt: null,
    accountId: "acc-salesloft",
  },
  {
    id: "sig-005",
    type: "leadership_change",
    headline: "New CRO hired from Salesforce",
    summary: "New revenue leaders typically audit the full sales stack within 90 days of joining.",
    detectedAt: daysAgo(4),
    source: "LinkedIn",
    seenAt: daysAgo(3),
    accountId: "acc-qualified",
  },
  {
    id: "sig-006",
    type: "expansion",
    headline: "Opened a new EMEA office in London",
    summary: "APAC and EMEA headcount targets doubled for the year; localization and enterprise hiring follow this pattern.",
    detectedAt: daysAgo(5),
    source: "6sense Newsroom",
    seenAt: null,
    accountId: "acc-6sense",
  },
  {
    id: "sig-007",
    type: "new_funding",
    headline: "Raised $225M Series F at $1.6B valuation",
    summary: "They will likely expand their platform and partner ecosystem aggressively over the next 18 months.",
    detectedAt: daysAgo(0),
    source: "TechCrunch",
    seenAt: null,
    accountId: "acc-clari",
  },
  {
    id: "sig-008",
    type: "hiring_surge",
    headline: "18 SDRs + 4 Sales Engineers roles open",
    summary: "Strong signal they are entering a new market segment — decision velocity is high right now.",
    detectedAt: daysAgo(6),
    source: "LinkedIn Jobs",
    seenAt: daysAgo(5),
    accountId: "acc-bombora",
  },
  {
    id: "sig-009",
    type: "intent_surge",
    headline: "Active research on data enrichment alternatives",
    summary: "Buying committee has been researching real-time visitor identification — suggesting active vendor evaluation.",
    detectedAt: daysAgo(1),
    source: "Bombora",
    seenAt: null,
    accountId: "acc-clearbit",
  },
  {
    id: "sig-010",
    type: "tech_change",
    headline: "Switched from Salesforce to HubSpot CRM",
    summary: "Ideal moment to introduce complementary ABM tooling that integrates natively with HubSpot.",
    detectedAt: daysAgo(7),
    source: "BuiltWith",
    seenAt: daysAgo(6),
    accountId: "acc-demandbase",
  },
  {
    id: "sig-011",
    type: "leadership_change",
    headline: "New VP Sales Engineering, ex-Snowflake",
    summary: "Track record of modernizing the pre-sales tech stack at Snowflake — a tailwind for our category.",
    detectedAt: daysAgo(3),
    source: "LinkedIn",
    seenAt: null,
    accountId: "acc-lattice",
  },
  {
    id: "sig-012",
    type: "expansion",
    headline: "Launched a mid-market product tier",
    summary: "New SKU opens a segment they previously left to competitors. Worth re-pricing the open opp.",
    detectedAt: daysAgo(8),
    source: "Gong Blog",
    seenAt: daysAgo(7),
    accountId: "acc-gong",
  },
  {
    id: "sig-013",
    type: "new_funding",
    headline: "Closed a $95M growth round",
    summary: "Confirms a multi-year investment horizon for their Pipeline Cloud platform expansion.",
    detectedAt: daysAgo(9),
    source: "Crunchbase",
    seenAt: daysAgo(8),
    accountId: "acc-qualified",
  },
  {
    id: "sig-014",
    type: "hiring_surge",
    headline: "22 RevOps & data roles posted this week",
    summary: "Strong indicator they are investing in their analytics infrastructure — opens tooling conversations.",
    detectedAt: daysAgo(2),
    source: "LinkedIn Jobs",
    seenAt: null,
    accountId: "acc-clari",
  },
  {
    id: "sig-015",
    type: "intent_surge",
    headline: "Spiked on pipeline generation research",
    summary: "Team researching outbound automation topics — may be evaluating tooling to supplement native ABM.",
    detectedAt: daysAgo(4),
    source: "Bombora",
    seenAt: null,
    accountId: "acc-6sense",
  },
  {
    id: "sig-016",
    type: "tech_change",
    headline: "Replaced Drift with Qualified for pipeline",
    summary: "Active vendor consolidation cycle — indicating openness to new conversational sales tooling.",
    detectedAt: daysAgo(10),
    source: "BuiltWith",
    seenAt: daysAgo(9),
    accountId: "acc-outreach",
  },
  {
    id: "sig-017",
    type: "leadership_change",
    headline: "VP of Product promoted to Chief Product Officer",
    summary: "Internal leadership transitions often spark a reassessment of vendor relationships.",
    detectedAt: daysAgo(11),
    source: "LinkedIn",
    seenAt: daysAgo(10),
    accountId: "acc-bombora",
  },
];

// ---------------------------------------------------------------------------
// MOCK_WATCHLIST_ACCOUNTS
// ---------------------------------------------------------------------------

export const MOCK_WATCHLIST_ACCOUNTS: WatchlistAccount[] = [
  {
    id: "acc-lattice",
    accountName: "Lattice",
    domain: "lattice.com",
    description: "People management platform helping HR and people teams run performance reviews, set goals, and develop employees. Primarily serves mid-market and enterprise companies scaling their people operations.",
    industry: "SaaS",
    revenue: "$50M–$100M ARR",
    employees: "501–1,000",
    location: "San Francisco, CA",
    addedAt: daysAgo(14),
    monitoredSignals: ["new_funding", "leadership_change", "hiring_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-lattice"),
    intentScore: 87,
    intentDelta: 11,
    intentLabel: "Hot",
  },
  {
    id: "acc-gong",
    accountName: "Gong",
    domain: "gong.io",
    description: "Revenue intelligence platform that captures and analyzes customer interactions across calls, emails, and meetings. Helps sales teams understand what's working and coach reps at scale.",
    industry: "SaaS",
    revenue: "$100M+ ARR",
    employees: "1,001–5,000",
    location: "San Francisco, CA",
    addedAt: daysAgo(20),
    monitoredSignals: ["hiring_surge", "expansion", "intent_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-gong"),
    intentScore: 92,
    intentDelta: 6,
    intentLabel: "Hot",
  },
  {
    id: "acc-outreach",
    accountName: "Outreach",
    domain: "outreach.io",
    description: "Sales execution platform for sequencing, prospecting, and pipeline management. Used by outbound sales teams to automate multi-channel outreach and surface deal risk early.",
    industry: "SaaS",
    revenue: "$100M+ ARR",
    employees: "1,001–5,000",
    location: "Seattle, WA",
    addedAt: daysAgo(5),
    monitoredSignals: ["intent_surge", "tech_change"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-outreach"),
    intentScore: 81,
    intentDelta: 4,
    intentLabel: "Hot",
  },
  {
    id: "acc-salesloft",
    accountName: "Salesloft",
    domain: "salesloft.com",
    description: "Sales engagement and revenue workflow platform. Helps revenue teams manage cadences, forecast deals, and coach sellers through the full sales cycle from prospecting to close.",
    industry: "SaaS",
    revenue: "$50M–$100M ARR",
    employees: "501–1,000",
    location: "Atlanta, GA",
    addedAt: daysAgo(10),
    monitoredSignals: ["tech_change", "hiring_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-salesloft"),
    intentScore: 55,
    intentDelta: -3,
    intentLabel: "Warm",
  },
  {
    id: "acc-qualified",
    accountName: "Qualified",
    domain: "qualified.com",
    description: "Pipeline generation platform for B2B companies using Salesforce. Identifies high-intent website visitors in real time and enables sales reps to engage them instantly via chat and AI agents.",
    industry: "SaaS",
    revenue: "$10M–$50M ARR",
    employees: "101–500",
    location: "San Francisco, CA",
    addedAt: daysAgo(7),
    monitoredSignals: ["leadership_change", "new_funding"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-qualified"),
    intentScore: 91,
    intentDelta: 8,
    intentLabel: "Hot",
  },
  {
    id: "acc-6sense",
    accountName: "6sense",
    domain: "6sense.com",
    description: "Account engagement platform using AI and intent data to surface in-market buyers. Helps B2B revenue teams prioritize accounts, personalize outreach, and forecast pipeline with predictive insights.",
    industry: "SaaS",
    revenue: "$100M+ ARR",
    employees: "1,001–5,000",
    location: "San Francisco, CA",
    addedAt: daysAgo(3),
    monitoredSignals: ["expansion", "intent_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-6sense"),
    intentScore: 78,
    intentDelta: -2,
    intentLabel: "Hot",
  },
  {
    id: "acc-clari",
    accountName: "Clari",
    domain: "clari.com",
    description: "Revenue operations platform that consolidates CRM data, call intelligence, and activity signals into a single forecast. Used by CROs and RevOps teams to eliminate revenue leak and improve win rates.",
    industry: "SaaS",
    revenue: "$100M+ ARR",
    employees: "501–1,000",
    location: "Sunnyvale, CA",
    addedAt: daysAgo(25),
    monitoredSignals: ["new_funding", "hiring_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-clari"),
    intentScore: 83,
    intentDelta: 9,
    intentLabel: "Hot",
  },
  {
    id: "acc-bombora",
    accountName: "Bombora",
    domain: "bombora.com",
    description: "B2B intent data provider aggregating content consumption signals from a cooperative of publisher websites. Helps marketing and sales teams identify accounts actively researching solutions in their category.",
    industry: "SaaS",
    revenue: "$10M–$50M ARR",
    employees: "101–500",
    location: "New York, NY",
    addedAt: daysAgo(18),
    monitoredSignals: ["hiring_surge", "leadership_change"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-bombora"),
    intentScore: 44,
    intentDelta: -14,
    intentLabel: "Warm",
  },
  {
    id: "acc-clearbit",
    accountName: "Clearbit",
    domain: "clearbit.com",
    description: "B2B data enrichment platform providing real-time firmographic, technographic, and contact data. Widely used to enrich CRM records, power lead scoring, and personalise marketing and sales workflows.",
    industry: "SaaS",
    revenue: "$10M–$50M ARR",
    employees: "101–500",
    location: "San Francisco, CA",
    addedAt: daysAgo(30),
    monitoredSignals: ["intent_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-clearbit"),
    intentScore: 31,
    intentDelta: -5,
    intentLabel: "Cold",
  },
  {
    id: "acc-demandbase",
    accountName: "Demandbase",
    domain: "demandbase.com",
    description: "Account-based marketing and sales intelligence platform. Combines first-party intent, advertising, and CRM data to help B2B teams identify, engage, and convert their highest-value target accounts.",
    industry: "SaaS",
    revenue: "$50M–$100M ARR",
    employees: "501–1,000",
    location: "San Francisco, CA",
    addedAt: daysAgo(12),
    monitoredSignals: ["tech_change", "intent_surge"],
    signals: MOCK_SIGNALS.filter((s) => s.accountId === "acc-demandbase"),
    intentScore: 58,
    intentDelta: 3,
    intentLabel: "Warm",
  },
];

// ---------------------------------------------------------------------------
// MOCK_ICP_RESULTS
// ---------------------------------------------------------------------------

export const MOCK_ICP_RESULTS: ICPAccount[] = [
  { id: "icp-001", companyName: "Lattice", domain: "lattice.com", industry: "SaaS", revenue: "$50M–$100M", employees: 750, location: "San Francisco, CA", icpScore: 96, isWatched: true },
  { id: "icp-002", companyName: "Gong", domain: "gong.io", industry: "SaaS", revenue: "$100M+", employees: 2400, location: "San Francisco, CA", icpScore: 94, isWatched: true },
  { id: "icp-003", companyName: "Clari", domain: "clari.com", industry: "SaaS", revenue: "$100M+", employees: 800, location: "Sunnyvale, CA", icpScore: 92, isWatched: true },
  { id: "icp-004", companyName: "Qualified", domain: "qualified.com", industry: "SaaS", revenue: "$10M–$50M", employees: 250, location: "San Francisco, CA", icpScore: 91, isWatched: true },
  { id: "icp-005", companyName: "6sense", domain: "6sense.com", industry: "SaaS", revenue: "$100M+", employees: 1800, location: "San Francisco, CA", icpScore: 89, isWatched: true },
  { id: "icp-006", companyName: "Outreach", domain: "outreach.io", industry: "SaaS", revenue: "$100M+", employees: 1200, location: "Seattle, WA", icpScore: 88, isWatched: true },
  { id: "icp-007", companyName: "Salesloft", domain: "salesloft.com", industry: "SaaS", revenue: "$50M–$100M", employees: 600, location: "Atlanta, GA", icpScore: 86, isWatched: true },
  { id: "icp-008", companyName: "Chorus.ai", domain: "chorus.ai", industry: "SaaS", revenue: "$10M–$50M", employees: 320, location: "San Francisco, CA", icpScore: 84, isWatched: false },
  { id: "icp-009", companyName: "Highspot", domain: "highspot.com", industry: "SaaS", revenue: "$50M–$100M", employees: 550, location: "Seattle, WA", icpScore: 83, isWatched: false },
  { id: "icp-010", companyName: "Seismic", domain: "seismic.com", industry: "SaaS", revenue: "$50M–$100M", employees: 700, location: "San Diego, CA", icpScore: 81, isWatched: false },
  { id: "icp-011", companyName: "Bombora", domain: "bombora.com", industry: "SaaS", revenue: "$10M–$50M", employees: 280, location: "New York, NY", icpScore: 79, isWatched: true },
  { id: "icp-012", companyName: "Clearbit", domain: "clearbit.com", industry: "SaaS", revenue: "$10M–$50M", employees: 200, location: "San Francisco, CA", icpScore: 78, isWatched: true },
  { id: "icp-013", companyName: "Demandbase", domain: "demandbase.com", industry: "SaaS", revenue: "$50M–$100M", employees: 650, location: "San Francisco, CA", icpScore: 77, isWatched: true },
  { id: "icp-014", companyName: "Apollo.io", domain: "apollo.io", industry: "SaaS", revenue: "$10M–$50M", employees: 450, location: "Remote", icpScore: 76, isWatched: false },
  { id: "icp-015", companyName: "ZoomInfo", domain: "zoominfo.com", industry: "SaaS", revenue: "$100M+", employees: 3000, location: "Vancouver, WA", icpScore: 74, isWatched: false },
  { id: "icp-016", companyName: "Drift", domain: "drift.com", industry: "SaaS", revenue: "$50M–$100M", employees: 500, location: "Boston, MA", icpScore: 73, isWatched: false },
  { id: "icp-017", companyName: "Intercom", domain: "intercom.com", industry: "SaaS", revenue: "$100M+", employees: 900, location: "San Francisco, CA", icpScore: 71, isWatched: false },
  { id: "icp-018", companyName: "HubSpot", domain: "hubspot.com", industry: "SaaS", revenue: "$100M+", employees: 7000, location: "Cambridge, MA", icpScore: 69, isWatched: false },
  { id: "icp-019", companyName: "Gainsight", domain: "gainsight.com", industry: "SaaS", revenue: "$50M–$100M", employees: 800, location: "San Francisco, CA", icpScore: 67, isWatched: false },
  { id: "icp-020", companyName: "Pendo", domain: "pendo.io", industry: "SaaS", revenue: "$10M–$50M", employees: 400, location: "Raleigh, NC", icpScore: 65, isWatched: false },
  { id: "icp-021", companyName: "Mixpanel", domain: "mixpanel.com", industry: "SaaS", revenue: "$10M–$50M", employees: 350, location: "San Francisco, CA", icpScore: 63, isWatched: false },
  { id: "icp-022", companyName: "Segment", domain: "segment.com", industry: "SaaS", revenue: "$50M–$100M", employees: 600, location: "San Francisco, CA", icpScore: 61, isWatched: false },
  { id: "icp-023", companyName: "Amplitude", domain: "amplitude.com", industry: "SaaS", revenue: "$50M–$100M", employees: 750, location: "San Francisco, CA", icpScore: 58, isWatched: false },
  { id: "icp-024", companyName: "Heap", domain: "heap.io", industry: "SaaS", revenue: "$10M–$50M", employees: 250, location: "San Francisco, CA", icpScore: 54, isWatched: false },
  { id: "icp-025", companyName: "FullStory", domain: "fullstory.com", industry: "SaaS", revenue: "$10M–$50M", employees: 320, location: "Atlanta, GA", icpScore: 51, isWatched: false },
];

// ---------------------------------------------------------------------------
// MOCK_PLAYBOOKS
// ---------------------------------------------------------------------------

export const MOCK_PLAYBOOKS: Record<string, PlaybookData> = {
  "acc-lattice": {
    accountId: "acc-lattice",
    accountName: "Lattice",
    thesis:
      "Lattice just closed a $50M Series D and hired a new VP of Sales Engineering from Snowflake. New leaders with fresh budget consistently rebuild their pre-sales and GTM stack within 90 days. The timing is ideal to lead with a technical value story backed by their Snowflake-native workflow.",
    fitHypotheses: [
      { text: "Their new VP of SE will want a modern demo and POC workflow within 60 days of joining", priority: "High" },
      { text: "Series D budget will unlock enterprise tooling decisions that were blocked before", priority: "High" },
      { text: "Their existing pre-sales tooling is likely 2+ years old given rapid headcount growth", priority: "Med" },
      { text: "HR-adjacent data workflows align with their People Management platform direction", priority: "Low" },
    ],
    landmines: [
      { text: "They may have a vendor locked in through existing Series C commitments", category: "Contractual" },
      { text: "New VP of SE is still building trust internally — avoid deals that need CFO sign-off in Q1", category: "Timing" },
      { text: "Snowflake partnership could create conflict if we compete on data layer", category: "Technical" },
    ],
    talkingPoints: [
      { text: "We natively integrate with Snowflake, which maps directly to their new SE leader's background and comfort zone." },
      { text: "Lattice's current growth rate of 40%+ YoY means their ops complexity is outpacing their current toolset." },
      { text: "Companies at Series D typically hit an inflection point where point solutions create more friction than value." },
    ],
    discoveryQuestions: [
      { text: "What does your current pre-sales workflow look like from opportunity to technical win?", actionLabel: "Probe gap", category: "Process" },
      { text: "How are you measuring the efficiency of your SE team today?", actionLabel: "Quantify pain", category: "Metrics" },
      { text: "What was the trigger for bringing in a new VP of SE at this stage?", actionLabel: "Understand urgency", category: "Leadership" },
      { text: "What does the ideal state look like for your GTM stack 12 months from now?", actionLabel: "Align vision", category: "Strategy" },
    ],
    nextActions: [
      { id: "na-001", text: "Send personalized intro email to new VP of Sales Engineering referencing Snowflake background", due: daysAgo(-2), done: false },
      { id: "na-002", text: "Request 20-min discovery call via LinkedIn (mutual connection exists)", due: daysAgo(-5), done: false },
      { id: "na-003", text: "Prepare Lattice-specific one-pager with Series D and Snowflake angle", due: daysAgo(-3), done: true },
      { id: "na-004", text: "Loop in AE to co-own the account and align on messaging", due: daysAgo(-7), done: false },
    ],
    timeline: [
      { date: daysAgo(14), event: "Account added to watchlist", type: "system" },
      { date: daysAgo(3), event: "Leadership change signal detected: new VP of SE hired", type: "system" },
      { date: daysAgo(1), event: "New funding signal: $50M Series D confirmed", type: "system" },
      { date: daysAgo(1), event: "Playbook generated", type: "system" },
    ],
    stakeholders: [
      { id: "sh-001", name: "Marcus Chen", title: "VP of Sales Engineering", role: "Champion", sentiment: "unknown", lastActiveDaysAgo: 3 },
      { id: "sh-002", name: "Sarah Goldstein", title: "CRO", role: "Economic Buyer", sentiment: "neutral", lastActiveDaysAgo: 12 },
      { id: "sh-003", name: "David Park", title: "Head of RevOps", role: "Influencer", sentiment: "positive", lastActiveDaysAgo: 5 },
      { id: "sh-004", name: "Priya Nair", title: "VP of Engineering", role: "Blocker", sentiment: "negative", lastActiveDaysAgo: 20 },
    ],
    generatedAt: daysAgo(1),
  },

  "acc-qualified": {
    accountId: "acc-qualified",
    accountName: "Qualified",
    thesis:
      "Qualified brought in a new CRO from Salesforce and simultaneously raised $95M in growth equity. The combination of fresh executive leadership and significant capital creates a perfect storm for vendor re-evaluation. Lead with pipeline efficiency and Salesforce ecosystem fit.",
    fitHypotheses: [
      { text: "Salesforce-background CRO will gravitate toward tools with deep Salesforce integration", priority: "High" },
      { text: "Growth equity mandate means they need to show ROI metrics fast — we can help instrumentalize that", priority: "High" },
      { text: "Their Pipeline Cloud expansion means they need complementary data infrastructure", priority: "Med" },
      { text: "Mid-stage growth means they are starting to feel the pain of manual RevOps work", priority: "Med" },
    ],
    landmines: [
      { text: "New CRO may have preferred vendors from Salesforce — research his past stack before first call", category: "Relationship" },
      { text: "Internal political dynamics post-funding can slow procurement by 30-60 days", category: "Timing" },
      { text: "They compete directly with some of our existing customers — handle carefully", category: "Commercial" },
    ],
    talkingPoints: [
      { text: "Our Salesforce-native architecture means zero switching cost in the CRM data layer — ideal for a Salesforce-background CRO." },
      { text: "Post-growth equity, investors expect pipeline efficiency metrics within 2 quarters — we accelerate that reporting." },
      { text: "Qualified's Pipeline Cloud and our platform are complementary, not competitive — we plug into their motion." },
    ],
    discoveryQuestions: [
      { text: "What metrics will the new CRO be evaluated on in the first 90 days?", actionLabel: "Map to ROI", category: "Leadership" },
      { text: "How are you currently tracking pipeline conversion rates by segment?", actionLabel: "Find gap", category: "Metrics" },
      { text: "What does your current Salesforce data hygiene process look like?", actionLabel: "Identify pain", category: "Technical" },
      { text: "Are there any tooling decisions that were on hold pending this funding round?", actionLabel: "Unlock budget", category: "Budget" },
    ],
    nextActions: [
      { id: "na-005", text: "Research new CRO's LinkedIn history and past stack at Salesforce", due: daysAgo(-1), done: true },
      { id: "na-006", text: "Draft exec-level outreach email referencing Pipeline Cloud expansion", due: daysAgo(-3), done: false },
      { id: "na-007", text: "Set Google Alert for Qualified + CRO name for real-time signals", due: daysAgo(-1), done: true },
      { id: "na-008", text: "Schedule internal pre-call strategy session with AE and SE", due: daysAgo(-5), done: false },
    ],
    timeline: [
      { date: daysAgo(7), event: "Account added to watchlist", type: "system" },
      { date: daysAgo(9), event: "New funding signal: $95M growth equity raised", type: "system" },
      { date: daysAgo(4), event: "Leadership change signal: new CRO hired from Salesforce", type: "system" },
      { date: daysAgo(4), event: "Discovery email sent to Head of RevOps", type: "email" },
      { date: daysAgo(2), event: "Playbook generated", type: "system" },
    ],
    stakeholders: [
      { id: "sh-005", name: "James Whitfield", title: "Chief Revenue Officer", role: "Economic Buyer", sentiment: "unknown", lastActiveDaysAgo: 4 },
      { id: "sh-006", name: "Anika Sharma", title: "VP of Revenue Operations", role: "Champion", sentiment: "positive", lastActiveDaysAgo: 2 },
      { id: "sh-007", name: "Tom Reyes", title: "Director of Sales Enablement", role: "Influencer", sentiment: "neutral", lastActiveDaysAgo: 8 },
      { id: "sh-008", name: "Lisa Huang", title: "VP of Finance", role: "Economic Buyer", sentiment: "neutral", lastActiveDaysAgo: 15 },
    ],
    generatedAt: daysAgo(2),
  },

  "acc-clari": {
    accountId: "acc-clari",
    accountName: "Clari",
    thesis:
      "Clari raised a $225M Series F and immediately posted 22 RevOps and data engineering roles. This level of data team hiring at scale indicates they are building or rebuilding internal data infrastructure — creating an ideal entry point for a platform conversation at the infrastructure layer.",
    fitHypotheses: [
      { text: "Massive data hiring wave means they need tooling that scales with a growing data org", priority: "High" },
      { text: "Series F capital creates multi-year budget certainty — enterprise contract terms are in play", priority: "High" },
      { text: "Revenue intelligence focus means they are a native buyer of adjacent analytics tooling", priority: "Med" },
      { text: "Their existing data stack may not scale to support the hiring velocity they are planning", priority: "Med" },
    ],
    landmines: [
      { text: "At $1.6B valuation, procurement cycles are formal and slow — expect 90+ day sales cycles", category: "Process" },
      { text: "Internal 'build vs. buy' debate is likely — have ROI data ready", category: "Technical" },
      { text: "Heavy investor scrutiny post-Series F means they will negotiate hard on pricing", category: "Commercial" },
    ],
    talkingPoints: [
      { text: "We compress the time-to-value for data infrastructure by 60% compared to in-house builds — critical at this hiring pace." },
      { text: "Revenue teams at Clari's scale generate data complexity that requires platform-grade solutions, not scripts." },
      { text: "A $225M raise means they have the budget to do this right the first time rather than patch solutions together." },
    ],
    discoveryQuestions: [
      { text: "What is driving the decision to hire 22 data roles now versus 6 months ago?", actionLabel: "Understand urgency", category: "Strategy" },
      { text: "Is there an internal data platform initiative underway, or are teams working in silos?", actionLabel: "Map architecture", category: "Technical" },
      { text: "How are you currently handling data quality and enrichment across your revenue data?", actionLabel: "Find pain", category: "Process" },
      { text: "What does success look like for the data org 18 months post-funding?", actionLabel: "Align vision", category: "Strategy" },
    ],
    nextActions: [
      { id: "na-009", text: "Identify the hiring manager for the data infrastructure roles on LinkedIn", due: daysAgo(-1), done: false },
      { id: "na-010", text: "Reach out to existing Clari contact in customer network for warm intro", due: daysAgo(-3), done: false },
      { id: "na-011", text: "Build Clari-specific ROI model showing build vs. buy at their scale", due: daysAgo(-5), done: false },
      { id: "na-012", text: "Add Clari to ABM sequence in Outreach with funding+hiring angle", due: daysAgo(-2), done: true },
    ],
    timeline: [
      { date: daysAgo(25), event: "Account added to watchlist", type: "system" },
      { date: daysAgo(0), event: "New funding signal: $225M Series F at $1.6B valuation", type: "system" },
      { date: daysAgo(2), event: "Hiring surge signal: 22 RevOps and data roles posted", type: "system" },
      { date: daysAgo(22), event: "Initial discovery email sent to VP of Data", type: "email" },
      { date: daysAgo(18), event: "Discovery call held — no decision maker present", type: "meeting" },
      { date: daysAgo(0), event: "Playbook regenerated post-funding news", type: "system" },
    ],
    stakeholders: [
      { id: "sh-009", name: "Kevin Torres", title: "VP of Data Engineering", role: "Champion", sentiment: "positive", lastActiveDaysAgo: 5 },
      { id: "sh-010", name: "Rachel Kim", title: "CFO", role: "Economic Buyer", sentiment: "neutral", lastActiveDaysAgo: 18 },
      { id: "sh-011", name: "Brian Patel", title: "Head of RevOps", role: "Influencer", sentiment: "positive", lastActiveDaysAgo: 3 },
      { id: "sh-012", name: "Michelle Foster", title: "Director of IT Security", role: "Blocker", sentiment: "negative", lastActiveDaysAgo: 10 },
      { id: "sh-013", name: "Jason Wu", title: "Senior Data Architect", role: "Ops", sentiment: "positive", lastActiveDaysAgo: 1 },
    ],
    generatedAt: daysAgo(0),
  },
};

// ---------------------------------------------------------------------------
// MOCK_PLAYBOOK_LIST — summary rows for the Playbook list view
// ---------------------------------------------------------------------------

export const MOCK_PLAYBOOK_LIST: PlaybookListItem[] = [
  {
    id: "pb-lattice",
    accountId: "acc-lattice",
    accountName: "Lattice",
    status: "Active",
    lastUpdated: daysAgo(1),
    nextAction: "Send personalized intro email to new VP of Sales Engineering",
  },
  {
    id: "pb-qualified",
    accountId: "acc-qualified",
    accountName: "Qualified",
    status: "Active",
    lastUpdated: daysAgo(2),
    nextAction: "Draft exec-level outreach email referencing Pipeline Cloud expansion",
  },
  {
    id: "pb-clari",
    accountId: "acc-clari",
    accountName: "Clari",
    status: "Active",
    lastUpdated: daysAgo(0),
    nextAction: "Identify the hiring manager for the data infrastructure roles on LinkedIn",
  },
  {
    id: "pb-gong",
    accountId: "acc-gong",
    accountName: "Gong",
    status: "Paused",
    lastUpdated: daysAgo(9),
    nextAction: "Re-engage once mid-market launch settles",
  },
  {
    id: "pb-6sense",
    accountId: "acc-6sense",
    accountName: "6sense",
    status: "Active",
    lastUpdated: daysAgo(4),
    nextAction: "Follow up on EMEA expansion with localization angle",
  },
];

// ---------------------------------------------------------------------------
// DEMO_ACCOUNTS — shown when user has no real watched accounts
// ---------------------------------------------------------------------------

export const DEMO_ACCOUNTS: WatchlistAccount[] = [
  {
    id: "demo-acc-1",
    accountName: "Gong",
    domain: "gong.io",
    industry: "SaaS",
    revenue: "$100M+",
    employees: "1001–5000",
    location: "San Francisco, CA",
    addedAt: daysAgo(10),
    monitoredSignals: ["hiring_surge", "expansion", "new_funding"],
    signals: [
      {
        id: "demo-sig-1",
        type: "hiring_surge",
        summary: "Gong posted 34 new sales and engineering roles this week, signaling a significant GTM ramp ahead of their annual conference.",
        detectedAt: daysAgo(2),
        source: "LinkedIn Jobs",
        seenAt: null,
        accountId: "demo-acc-1",
      },
      {
        id: "demo-sig-2",
        type: "expansion",
        summary: "Gong launched a new mid-market product tier, opening a segment they previously left to competitors.",
        detectedAt: daysAgo(7),
        source: "Gong Blog",
        seenAt: daysAgo(6),
        accountId: "demo-acc-1",
      },
    ],
    intentScore: 82,
    intentLabel: "Hot",
  },
  {
    id: "demo-acc-2",
    accountName: "Outreach",
    domain: "outreach.io",
    industry: "SaaS",
    revenue: "$100M+",
    employees: "1001–5000",
    location: "Seattle, WA",
    addedAt: daysAgo(15),
    monitoredSignals: ["intent_surge", "tech_change"],
    signals: [
      {
        id: "demo-sig-3",
        type: "intent_surge",
        summary: "Outreach's team is researching 'revenue intelligence' and 'conversation analytics' heavily — a buying signal for complementary tooling.",
        detectedAt: daysAgo(3),
        source: "Bombora",
        seenAt: null,
        accountId: "demo-acc-2",
      },
    ],
    intentScore: 61,
    intentLabel: "Warm",
  },
  {
    id: "demo-acc-3",
    accountName: "Clari",
    domain: "clari.com",
    industry: "SaaS",
    revenue: "$100M+",
    employees: "501–1000",
    location: "Sunnyvale, CA",
    addedAt: daysAgo(20),
    monitoredSignals: ["new_funding", "hiring_surge"],
    signals: [
      {
        id: "demo-sig-4",
        type: "new_funding",
        summary: "Clari raised $225M Series F at a $1.6B valuation — one of the largest revenue intelligence funding rounds on record.",
        detectedAt: daysAgo(0),
        source: "TechCrunch",
        seenAt: null,
        accountId: "demo-acc-3",
      },
      {
        id: "demo-sig-5",
        type: "hiring_surge",
        summary: "Clari posted 22 RevOps and data engineering roles this week, indicating a major platform build-out.",
        detectedAt: daysAgo(2),
        source: "LinkedIn Jobs",
        seenAt: null,
        accountId: "demo-acc-3",
      },
    ],
    intentScore: 88,
    intentLabel: "Hot",
  },
  {
    id: "demo-acc-4",
    accountName: "Demandbase",
    domain: "demandbase.com",
    industry: "SaaS",
    revenue: "$50M–$100M",
    employees: "501–1000",
    location: "San Francisco, CA",
    addedAt: daysAgo(8),
    monitoredSignals: ["tech_change"],
    signals: [
      {
        id: "demo-sig-6",
        type: "tech_change",
        summary: "Demandbase migrated from Salesforce to HubSpot CRM — a major platform change that creates a window for complementary ABM tooling integrations.",
        detectedAt: daysAgo(7),
        source: "BuiltWith",
        seenAt: daysAgo(6),
        accountId: "demo-acc-4",
      },
    ],
    intentScore: 53,
    intentLabel: "Warm",
  },
  {
    id: "demo-acc-5",
    accountName: "Bombora",
    domain: "bombora.com",
    industry: "SaaS",
    revenue: "$10M–$50M",
    employees: "101–500",
    location: "New York, NY",
    addedAt: daysAgo(25),
    monitoredSignals: ["leadership_change", "hiring_surge"],
    signals: [
      {
        id: "demo-sig-7",
        type: "leadership_change",
        summary: "Bombora promoted their VP of Product to Chief Product Officer — a title change that typically signals a product-led growth pivot.",
        detectedAt: daysAgo(11),
        source: "LinkedIn",
        seenAt: daysAgo(10),
        accountId: "demo-acc-5",
      },
    ],
    intentScore: 38,
    intentLabel: "Cold",
  },
];
